# Generated by Django 4.2.2 on 2023-12-30 17:38

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapters_Society_and_Affinity_Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=150)),
                ('primary', models.IntegerField(default=0)),
                ('short_form', models.CharField(blank=True, max_length=20, null=True)),
                ('primary_color_code', models.CharField(blank=True, max_length=20, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sc_ag_logos/')),
            ],
            options={
                'verbose_name': 'Chapters-Societies-Affinity Group',
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=40)),
                ('team_short_description', ckeditor.fields.RichTextField(blank=True, max_length=200, null=True)),
                ('primary', models.IntegerField(default=0)),
                ('team_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='port.chapters_society_and_affinity_groups')),
            ],
        ),
        migrations.CreateModel(
            name='Roles_and_Position',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=40)),
                ('is_eb_member', models.BooleanField(default=False)),
                ('is_sc_ag_eb_member', models.BooleanField(default=False)),
                ('is_officer', models.BooleanField(default=False)),
                ('is_co_ordinator', models.BooleanField(default=False)),
                ('is_faculty', models.BooleanField(default=False)),
                ('is_mentor', models.BooleanField(default=False)),
                ('is_core_volunteer', models.BooleanField(default=False)),
                ('role_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='port.chapters_society_and_affinity_groups')),
            ],
            options={
                'verbose_name': 'Registered positions',
            },
        ),
        migrations.CreateModel(
            name='Panels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=40)),
                ('creation_time', models.DateTimeField(blank=True, null=True)),
                ('current', models.BooleanField(default=False)),
                ('panel_end_time', models.DateTimeField(blank=True, null=True)),
                ('panel_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='port.chapters_society_and_affinity_groups')),
            ],
            options={
                'verbose_name': 'IEEE NSU SB Panels',
            },
        ),
    ]
