# Generated by Django 4.2.2 on 2024-01-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles_and_position',
            name='rank',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
