# Generated by Django 4.2.2 on 2024-01-02 08:30

import ckeditor.fields
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='team_description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='team_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='Teams/team_images/'),
        ),
    ]
