# Generated by Django 4.2.2 on 2024-01-02 13:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0002_teams_team_description_teams_team_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='team_description',
        ),
        migrations.AddField(
            model_name='teams',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='team_short_description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=500, null=True),
        ),
    ]
