# Generated by Django 4.2.2 on 2024-01-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0003_remove_teams_team_description_teams_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles_and_position',
            name='is_volunteer',
            field=models.BooleanField(default=False),
        ),
    ]
