# Generated by Django 4.0.5 on 2023-01-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0003_chapters_society_and_affinity_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapters_society_and_affinity_groups',
            options={'verbose_name': 'Chapters-Societies-Affinity Group'},
        ),
        migrations.AlterField(
            model_name='chapters_society_and_affinity_groups',
            name='group_name',
            field=models.CharField(max_length=150),
        ),
    ]
