# Generated by Django 4.2.2 on 2024-01-04 13:10

import ckeditor.fields
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0004_roles_and_position_is_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapters_society_and_affinity_groups',
            name='about_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapters_society_and_affinity_groups',
            name='background_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/societies & ag/background image/'),
        ),
        migrations.AddField(
            model_name='chapters_society_and_affinity_groups',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='chapters_society_and_affinity_groups',
            name='contact_messages',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapters_society_and_affinity_groups',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chapters_society_and_affinity_groups',
            name='how_to_join',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapters_society_and_affinity_groups',
            name='mission_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapters_society_and_affinity_groups',
            name='mission_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/societies & ag/mission picture/'),
        ),
        migrations.AddField(
            model_name='chapters_society_and_affinity_groups',
            name='sc_ag_logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/Societies & AG/logos/'),
        ),
        migrations.AddField(
            model_name='chapters_society_and_affinity_groups',
            name='vision_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapters_society_and_affinity_groups',
            name='vision_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/societies & ag/vision picture/'),
        ),
        migrations.AddField(
            model_name='chapters_society_and_affinity_groups',
            name='what_activites_it_has',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapters_society_and_affinity_groups',
            name='what_is_this_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapters_society_and_affinity_groups',
            name='why_join_it',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
