# Generated by Django 4.2.2 on 2024-01-15 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0004_alter_roles_and_position_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roles_and_position',
            options={'ordering': ['-rank'], 'verbose_name': 'Registered positions'},
        ),
    ]
