# Generated by Django 4.2.2 on 2024-01-04 16:38

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0005_chapters_society_and_affinity_groups_about_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapters_society_and_affinity_groups',
            name='about_description',
            field=models.TextField(blank=True, null=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='chapters_society_and_affinity_groups',
            name='background_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/societies & ag/background image/', verbose_name='Background Image'),
        ),
        migrations.AlterField(
            model_name='chapters_society_and_affinity_groups',
            name='how_to_join',
            field=models.TextField(blank=True, null=True, verbose_name='How to join it ?'),
        ),
        migrations.AlterField(
            model_name='chapters_society_and_affinity_groups',
            name='mission_description',
            field=models.TextField(blank=True, null=True, verbose_name='Mission'),
        ),
        migrations.AlterField(
            model_name='chapters_society_and_affinity_groups',
            name='mission_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/societies & ag/mission picture/', verbose_name='Mission Image'),
        ),
        migrations.AlterField(
            model_name='chapters_society_and_affinity_groups',
            name='sc_ag_logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/Societies & AG/logos/', verbose_name='About Image'),
        ),
        migrations.AlterField(
            model_name='chapters_society_and_affinity_groups',
            name='vision_description',
            field=models.TextField(blank=True, null=True, verbose_name='Vission'),
        ),
        migrations.AlterField(
            model_name='chapters_society_and_affinity_groups',
            name='vision_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/societies & ag/vision picture/', verbose_name='Vission Image'),
        ),
        migrations.AlterField(
            model_name='chapters_society_and_affinity_groups',
            name='what_activites_it_has',
            field=models.TextField(blank=True, null=True, verbose_name='What activities we usally do ?'),
        ),
        migrations.AlterField(
            model_name='chapters_society_and_affinity_groups',
            name='what_is_this_description',
            field=models.TextField(blank=True, null=True, verbose_name='What is it about ?'),
        ),
        migrations.AlterField(
            model_name='chapters_society_and_affinity_groups',
            name='why_join_it',
            field=models.TextField(blank=True, null=True, verbose_name='Why join it ?'),
        ),
    ]
