# Generated by Django 4.2.2 on 2023-08-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0005_roles_and_position_panel_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roles_and_position',
            old_name='panel_member',
            new_name='is_eb_member',
        ),
        migrations.AddField(
            model_name='roles_and_position',
            name='is_officer',
            field=models.BooleanField(default=False),
        ),
    ]
