# Generated by Django 4.2.2 on 2024-01-15 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0005_alter_roles_and_position_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teams',
            options={'ordering': ['primary', 'is_active'], 'verbose_name': 'Registered Team'},
        ),
    ]
