# Generated by Django 4.2.2 on 2024-01-04 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0006_alter_chapters_society_and_affinity_groups_about_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapters_society_and_affinity_groups',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='chapters_society_and_affinity_groups',
            name='contact_messages',
        ),
        migrations.RemoveField(
            model_name='chapters_society_and_affinity_groups',
            name='contact_name',
        ),
    ]
