# Generated by Django 4.2.2 on 2023-08-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0006_rename_panel_member_roles_and_position_is_eb_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles_and_position',
            name='is_faculty',
            field=models.BooleanField(default=False),
        ),
    ]
