# Generated by Django 4.2.2 on 2024-01-04 16:47

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0007_remove_chapters_society_and_affinity_groups_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapters_society_and_affinity_groups',
            name='vision_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/societies & ag/vision picture/', verbose_name='Vision Image'),
        ),
        migrations.AlterField(
            model_name='chapters_society_and_affinity_groups',
            name='what_activites_it_has',
            field=models.TextField(blank=True, null=True, verbose_name='What activities we usually do ?'),
        ),
    ]
