# Generated by Django 4.2.2 on 2023-08-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0007_roles_and_position_is_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles_and_position',
            name='id2',
            field=models.IntegerField(default=0),
        ),
    ]
