# Generated by Django 4.2.2 on 2024-01-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0008_alter_chapters_society_and_affinity_groups_vision_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapters_society_and_affinity_groups',
            name='about_description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='chapters_society_and_affinity_groups',
            name='how_to_join',
            field=models.TextField(blank=True, default='', null=True, verbose_name='How to join it ?'),
        ),
        migrations.AlterField(
            model_name='chapters_society_and_affinity_groups',
            name='mission_description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Mission'),
        ),
        migrations.AlterField(
            model_name='chapters_society_and_affinity_groups',
            name='vision_description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Vission'),
        ),
        migrations.AlterField(
            model_name='chapters_society_and_affinity_groups',
            name='what_activites_it_has',
            field=models.TextField(blank=True, default='', null=True, verbose_name='What activities we usually do ?'),
        ),
        migrations.AlterField(
            model_name='chapters_society_and_affinity_groups',
            name='what_is_this_description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='What is it about ?'),
        ),
        migrations.AlterField(
            model_name='chapters_society_and_affinity_groups',
            name='why_join_it',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Why join it ?'),
        ),
    ]
