# Generated by Django 4.2.2 on 2023-08-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0009_remove_roles_and_position_id2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles_and_position',
            name='id',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
