# Generated by Django 4.2.2 on 2024-01-15 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0009_alter_teams_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teams',
            options={'ordering': ['-is_active', 'primary'], 'verbose_name': 'Registered Team'},
        ),
    ]
