# Generated by Django 4.2.2 on 2024-01-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0009_alter_chapters_society_and_affinity_groups_about_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapters_society_and_affinity_groups',
            name='page_title',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Page Title'),
        ),
        migrations.AddField(
            model_name='chapters_society_and_affinity_groups',
            name='secondary_paragraph',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Second Paragraph'),
        ),
    ]
