# Generated by Django 4.2.2 on 2024-01-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0010_chapters_society_and_affinity_groups_page_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapters_society_and_affinity_groups',
            name='page_title',
            field=models.TextField(blank=True, default='about', null=True, verbose_name='Page Title'),
        ),
    ]
