# Generated by Django 4.2.2 on 2024-01-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0011_alter_teams_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapters_society_and_affinity_groups',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='main_website_files/societies & ag/background image/', verbose_name='Background Image'),
        ),
        migrations.AlterField(
            model_name='chapters_society_and_affinity_groups',
            name='mission_picture',
            field=models.ImageField(blank=True, null=True, upload_to='main_website_files/societies & ag/mission picture/', verbose_name='Mission Image'),
        ),
        migrations.AlterField(
            model_name='chapters_society_and_affinity_groups',
            name='vision_picture',
            field=models.ImageField(blank=True, null=True, upload_to='main_website_files/societies & ag/vision picture/', verbose_name='Vision Image'),
        ),
    ]
