# Generated by Django 4.2.2 on 2024-01-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0011_alter_chapters_society_and_affinity_groups_page_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapters_society_and_affinity_groups',
            name='page_title',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Page Title'),
        ),
    ]
