# Generated by Django 3.2.16 on 2023-09-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0012_teams_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapters_society_and_affinity_groups',
            name='primary',
            field=models.IntegerField(default=0),
        ),
    ]
