# Generated by Django 4.2.2 on 2024-01-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0012_alter_chapters_society_and_affinity_groups_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapters_society_and_affinity_groups',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='chapters_society_and_affinity_groups',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
