# Generated by Django 4.2.2 on 2024-01-06 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0013_chapters_society_and_affinity_groups_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapters_society_and_affinity_groups',
            name='short_form_2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
