# Generated by Django 3.2.16 on 2023-09-06 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0013_chapters_society_and_affinity_groups_primary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Society_Chapters_AG_Roles_and_Positions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('position_name', models.CharField(max_length=50)),
                ('is_faculty_position', models.BooleanField(default=False)),
                ('is_eb_position', models.BooleanField(default=False)),
                ('is_officer_position', models.BooleanField(default=False)),
                ('sc_ag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='port.chapters_society_and_affinity_groups')),
            ],
            options={
                'verbose_name': 'Society, Chapters & Affinity Group Registered Positions',
            },
        ),
    ]
