# Generated by Django 4.2.2 on 2024-02-09 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0013_alter_chapters_society_and_affinity_groups_background_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerAwards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_award_name', models.CharField(max_length=100, verbose_name='Name of Award')),
                ('rank_of_awards', models.IntegerField(default=0)),
                ('award_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='port.chapters_society_and_affinity_groups')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='port.panels')),
            ],
            options={
                'verbose_name': 'Volunteer Award',
                'ordering': ['-rank_of_awards'],
            },
        ),
    ]
