# Generated by Django 4.2.2 on 2024-02-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0014_volunteerawards'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillSetTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_type', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Skill set Types',
            },
        ),
    ]
