# Generated by Django 4.2.2 on 2024-01-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0014_chapters_society_and_affinity_groups_short_form_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapters_society_and_affinity_groups',
            name='secondary_color_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chapters_society_and_affinity_groups',
            name='text_color_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
