# Generated by Django 4.2.2 on 2024-01-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0015_chapters_society_and_affinity_groups_secondary_color_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapters_society_and_affinity_groups',
            name='mission_vision_color_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
