# Generated by Django 4.2.2 on 2023-09-07 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0015_auto_20230906_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles_and_position',
            name='role_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='port.chapters_society_and_affinity_groups'),
        ),
        migrations.AddField(
            model_name='teams',
            name='team_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='port.chapters_society_and_affinity_groups'),
        ),
    ]
