# Generated by Django 4.2.2 on 2023-09-07 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ieee_nsu_sb_pes_sbc', '0003_remove_pesmembers_position_remove_pesmembers_team'),
        ('port', '0016_roles_and_position_role_of_teams_team_of'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='society_chapters_ag_teams',
            name='chapter_id',
        ),
        migrations.DeleteModel(
            name='Society_Chapters_AG_Roles_and_Positions',
        ),
        migrations.DeleteModel(
            name='Society_Chapters_AG_Teams',
        ),
    ]
