# Generated by Django 4.2.2 on 2024-01-12 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0016_chapters_society_and_affinity_groups_mission_vision_color_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapters_society_and_affinity_groups',
            name='sc_ag_logo',
        ),
    ]
