# Generated by Django 4.2.2 on 2024-01-13 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0017_remove_chapters_society_and_affinity_groups_sc_ag_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapters_society_and_affinity_groups',
            name='logo',
        ),
    ]
