# Generated by Django 4.2.2 on 2023-09-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0017_remove_society_chapters_ag_teams_chapter_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles_and_position',
            name='is_sc_ag_eb_member',
            field=models.BooleanField(default=False),
        ),
    ]
