# Generated by Django 4.2.2 on 2023-10-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0018_roles_and_position_is_sc_ag_eb_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles_and_position',
            name='is_co_ordinator',
            field=models.BooleanField(default=False),
        ),
    ]
