# Generated by Django 4.2.2 on 2023-10-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0019_roles_and_position_is_co_ordinator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=40)),
                ('current', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'IEEE NSU SB Panels',
            },
        ),
    ]
