# Generated by Django 4.2.2 on 2023-10-29 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0021_panels_create_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panels',
            old_name='create_time',
            new_name='creation_time',
        ),
    ]
