# Generated by Django 4.2.2 on 2023-11-03 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0022_rename_create_time_panels_creation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='panels',
            name='panel_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='port.chapters_society_and_affinity_groups'),
        ),
    ]
