# Generated by Django 4.2.2 on 2024-01-13 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0017_alter_chapters_society_and_affinity_groups_background_image_and_more'),
        ('port', '0022_alter_chapters_society_and_affinity_groups_background_image_and_more'),
    ]

    operations = [
    ]
