# Generated by Django 4.2.2 on 2023-11-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0023_panels_panel_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='panels',
            name='panel_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
