# Generated by Django 4.2.2 on 2023-11-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0024_panels_panel_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles_and_position',
            name='is_mentor',
            field=models.BooleanField(default=False),
        ),
    ]
