# Generated by Django 4.2.2 on 2023-12-07 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0026_chapters_society_and_affinity_groups_color_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapters_society_and_affinity_groups',
            old_name='color_code',
            new_name='primary_color_code',
        ),
    ]
