# Generated by Django 4.2.2 on 2023-12-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0027_rename_color_code_chapters_society_and_affinity_groups_primary_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles_and_position',
            name='is_volunteer',
            field=models.BooleanField(default=False),
        ),
    ]
