# Generated by Django 4.2.2 on 2023-12-13 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0028_roles_and_position_is_volunteer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roles_and_position',
            old_name='is_volunteer',
            new_name='is_core_volunteer',
        ),
    ]
