# Generated by Django 4.2.2 on 2023-12-30 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('port', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renewal_Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=30)),
                ('session_time', models.DateField()),
            ],
            options={
                'verbose_name': 'Renewal Session',
            },
        ),
        migrations.CreateModel(
            name='Renewal_requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('ieee_id', models.BigIntegerField(default=0)),
                ('nsu_id', models.BigIntegerField(default=0)),
                ('name', models.CharField(default='null', max_length=100)),
                ('contact_no', models.CharField(default='null', max_length=30)),
                ('email_associated', models.EmailField(max_length=254)),
                ('email_ieee', models.EmailField(blank=True, max_length=254, null=True)),
                ('ieee_account_password', models.CharField(max_length=500)),
                ('ieee_renewal_check', models.BooleanField(default=False)),
                ('pes_renewal_check', models.BooleanField(default=False)),
                ('ras_renewal_check', models.BooleanField(default=False)),
                ('ias_renewal_check', models.BooleanField(default=False)),
                ('wie_renewal_check', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(blank=True, max_length=80, null=True)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('renewal_status', models.BooleanField(default=False)),
                ('view_status', models.BooleanField(default=False)),
                ('official_comment', models.CharField(blank=True, max_length=150, null=True)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership_development_team.renewal_sessions')),
            ],
            options={
                'verbose_name': 'Renewal Requests',
            },
        ),
        migrations.CreateModel(
            name='Renewal_Form_Info',
            fields=[
                ('form_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('form_description', models.TextField(blank=True, max_length=1000, null=True)),
                ('ieee_membership_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('ieee_ras_membership_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('ieee_pes_membership_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('ieee_ias_membership_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('ieee_wie_membership_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('bkash_payment_number', models.CharField(blank=True, max_length=20, null=True)),
                ('nagad_payment_number', models.CharField(blank=True, max_length=20, null=True)),
                ('further_contact_member_id', models.CharField(blank=True, max_length=50, null=True)),
                ('accepting_response', models.BooleanField(default=False)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membership_development_team.renewal_sessions')),
            ],
            options={
                'verbose_name': 'Renewal Form Detail',
            },
        ),
        migrations.CreateModel(
            name='Portal_Joining_Requests',
            fields=[
                ('ieee_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('nsu_id', models.BigIntegerField()),
                ('email_ieee', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_nsu', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_personal', models.EmailField(max_length=254)),
                ('major', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=16, null=True)),
                ('home_address', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=7, null=True)),
                ('facebook_url', models.URLField(blank=True, max_length=500, null=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=500, null=True)),
                ('application_status', models.BooleanField(default=False)),
                ('view_status', models.BooleanField(default=False)),
                ('position', models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='port.roles_and_position')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='port.teams')),
            ],
            options={
                'verbose_name': 'Portal Joining Requests',
            },
        ),
    ]
