# Generated by Django 4.1.2 on 2022-12-09 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0010_alter_members_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renewal_Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=30)),
                ('session_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Renewal_requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_personal', models.EmailField(max_length=254)),
                ('ieee_account_password', models.CharField(max_length=50)),
                ('renewal_status', models.BooleanField(default=False)),
                ('view_status', models.BooleanField(default=False)),
                ('ieee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.members')),
                ('session_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership_development_team.renewal_sessions')),
            ],
        ),
    ]
