# Generated by Django 4.1.2 on 2022-12-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_development_team', '0002_alter_renewal_sessions_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewal_requests',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='renewal_requests',
            name='ieee_renewal_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='renewal_requests',
            name='pes_renewal_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='renewal_requests',
            name='ras_renewal_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='renewal_requests',
            name='transaction_id',
            field=models.CharField(default='Self', max_length=50),
        ),
        migrations.AddField(
            model_name='renewal_requests',
            name='wie_renewal_check',
            field=models.BooleanField(default=False),
        ),
    ]
