# Generated by Django 4.2.2 on 2024-01-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_development_team', '0002_portal_joining_requests_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portal_joining_requests',
            name='nsu_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
