# Generated by Django 4.2.2 on 2024-03-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_development_team', '0002_alter_portal_joining_requests_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birthday_Email_Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Birthday Email Records',
            },
        ),
    ]
