# Generated by Django 4.1.2 on 2022-12-10 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_members_session'),
        ('membership_development_team', '0003_renewal_requests_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renewal_requests',
            name='ieee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.members'),
        ),
    ]
