# Generated by Django 4.2.2 on 2024-01-12 20:56

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('membership_development_team', '0003_alter_portal_joining_requests_nsu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portal_joining_requests',
            name='user_profile_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='user_profile_pictures/'),
        ),
    ]
