# Generated by Django 4.1.2 on 2022-12-10 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership_development_team', '0004_alter_renewal_requests_ieee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renewal_requests',
            name='ieee_id',
        ),
    ]
