# Generated by Django 4.1.2 on 2022-12-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_development_team', '0005_remove_renewal_requests_ieee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewal_requests',
            name='contact_no',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AddField(
            model_name='renewal_requests',
            name='name',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
