# Generated by Django 4.1.2 on 2022-12-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_development_team', '0006_renewal_requests_contact_no_renewal_requests_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewal_requests',
            name='official_comment',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
