# Generated by Django 4.1.2 on 2022-12-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_development_team', '0007_renewal_requests_official_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewal_requests',
            name='ias_renewal_check',
            field=models.BooleanField(default=False),
        ),
    ]
