# Generated by Django 4.1.2 on 2022-12-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_development_team', '0008_renewal_requests_ias_renewal_check'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='renewal_requests',
            options={'verbose_name': 'Renewal Requests'},
        ),
        migrations.AlterField(
            model_name='renewal_requests',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
