# Generated by Django 4.0.5 on 2023-01-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_development_team', '0009_alter_renewal_requests_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renewal_requests',
            name='ieee_account_password',
            field=models.CharField(max_length=500),
        ),
    ]
