# Generated by Django 4.0.5 on 2023-01-03 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership_development_team', '0011_renewal_requests_encrypt_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renewal_requests',
            name='encrypt_key',
        ),
    ]
