# Generated by Django 4.0.5 on 2023-01-10 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0002_roles_and_position'),
        ('membership_development_team', '0012_remove_renewal_requests_encrypt_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portal_Joining_Requests',
            fields=[
                ('ieee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('nsu_id', models.IntegerField()),
                ('email_ieee', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_personal', models.EmailField(max_length=254)),
                ('major', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=16, null=True)),
                ('home_address', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=7, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('position', models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='port.roles_and_position')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='port.teams')),
            ],
            options={
                'verbose_name': 'Portal Joining Requests',
            },
        ),
    ]
