# Generated by Django 4.0.5 on 2023-01-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_development_team', '0013_portal_joining_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='portal_joining_requests',
            name='application_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portal_joining_requests',
            name='view_status',
            field=models.BooleanField(default=False),
        ),
    ]
