# Generated by Django 3.2.16 on 2023-01-31 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20230131_2310'),
        ('membership_development_team', '0014_portal_joining_requests_application_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renewal_Form_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_description', models.CharField(blank=True, max_length=700, null=True)),
                ('ieee_membership', models.CharField(blank=True, max_length=50, null=True)),
                ('ieee_ras_membership', models.CharField(blank=True, max_length=50, null=True)),
                ('ieee_pes_membership', models.CharField(blank=True, max_length=50, null=True)),
                ('ieee_ias_membership', models.CharField(blank=True, max_length=50, null=True)),
                ('ieee_wie_membership', models.CharField(blank=True, max_length=50, null=True)),
                ('bkash_payment_number', models.CharField(blank=True, max_length=20, null=True)),
                ('further_contact_member_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.members')),
            ],
            options={
                'verbose_name': 'Renewal Form Details',
            },
        ),
    ]
