# Generated by Django 3.2.16 on 2023-09-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_development_team', '0019_alter_renewal_form_info_further_contact_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='portal_joining_requests',
            name='email_nsu',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
