# Generated by Django 4.2.2 on 2023-10-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_development_team', '0020_portal_joining_requests_email_nsu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='renewal_requests',
            old_name='email_personal',
            new_name='email_associated',
        ),
        migrations.AddField(
            model_name='renewal_requests',
            name='email_ieee',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='renewal_requests',
            name='ieee_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
