# Generated by Django 4.2.2 on 2023-10-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_development_team', '0021_rename_email_personal_renewal_requests_email_associated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewal_form_info',
            name='nagad_payment_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
