# Generated by Django 4.2.2 on 2023-10-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_development_team', '0022_renewal_form_info_nagad_payment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renewal_form_info',
            name='form_description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
