# Generated by Django 4.2.2 on 2023-10-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_development_team', '0023_alter_renewal_form_info_form_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewal_requests',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
