# Generated by Django 4.2.2 on 2023-10-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_development_team', '0024_renewal_requests_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renewal_requests',
            name='ieee_id',
            field=models.IntegerField(default=0),
        ),
    ]
