# Generated by Django 4.2.2 on 2023-10-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_development_team', '0025_alter_renewal_requests_ieee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewal_requests',
            name='nsu_id',
            field=models.IntegerField(default=0),
        ),
    ]
