# Generated by Django 4.2.2 on 2023-11-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_development_team', '0026_renewal_requests_nsu_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewal_form_info',
            name='accepting_response',
            field=models.BooleanField(default=False),
        ),
    ]
