# Generated by Django 4.2.2 on 2023-12-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_development_team', '0027_renewal_form_info_accepting_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renewal_requests',
            name='ieee_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='renewal_requests',
            name='nsu_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
