# Generated by Django 4.2.2 on 2023-12-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_development_team', '0028_alter_renewal_requests_ieee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portal_joining_requests',
            name='ieee_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='portal_joining_requests',
            name='nsu_id',
            field=models.BigIntegerField(),
        ),
    ]
