# Generated by Django 4.2.2 on 2023-12-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_development_team', '0029_alter_portal_joining_requests_ieee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portal_joining_requests',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='portal_joining_requests',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
