# Generated by Django 4.2.2 on 2023-12-30 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('port', '0001_initial'),
        ('recruitment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membership_development_team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni_Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', django_resized.forms.ResizedImageField(blank=True, crop=None, default='user_profile_pictures/default_profile_picture.png', force_format='JPEG', keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='panel_profile_pictures/')),
                ('linkedin_link', models.URLField(blank=True, max_length=100, null=True)),
                ('facebook_link', models.URLField(blank=True, max_length=100, null=True)),
                ('email', models.URLField(blank=True, max_length=50, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=50, null=True)),
                ('ieee_collaboratec', models.URLField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Ex Panel Members',
            },
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('ieee_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('nsu_id', models.BigIntegerField()),
                ('email_ieee', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_personal', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_nsu', models.EmailField(blank=True, max_length=254, null=True)),
                ('major', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=16, null=True)),
                ('home_address', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=7, null=True)),
                ('facebook_url', models.URLField(blank=True, max_length=500, null=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=500, null=True)),
                ('user_profile_picture', django_resized.forms.ResizedImageField(crop=None, default='user_profile_pictures/default_profile_picture.png', force_format='JPEG', keep_meta=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='user_profile_pictures/')),
                ('is_active_member', models.BooleanField(default=False)),
                ('last_renewal_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membership_development_team.renewal_sessions')),
                ('position', models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='port.roles_and_position')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.recruitment_session')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='port.teams')),
            ],
            options={
                'verbose_name': 'INSB Registered Members',
            },
        ),
        migrations.CreateModel(
            name='User_IP_Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.TextField(default=None)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Visitors on Main Website',
            },
        ),
        migrations.CreateModel(
            name='ResetPasswordTokenTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Reset Password Tokens',
            },
        ),
        migrations.CreateModel(
            name='Panel_Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.alumni_members')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.members')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='port.roles_and_position')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='port.teams')),
                ('tenure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='port.panels')),
            ],
            options={
                'verbose_name': 'Panel Members (Whole Tenure)',
            },
        ),
    ]
