# Generated by Django 4.1.2 on 2022-11-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('ieee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('nsu_id', models.IntegerField()),
                ('email_ieee', models.EmailField(max_length=254)),
                ('email_personal', models.EmailField(max_length=254)),
                ('contact_no', models.CharField(blank=True, max_length=16, null=True)),
                ('home_address', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=7)),
                ('facebook_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'INSB Registered Members',
            },
        ),
    ]
