# Generated by Django 4.1.2 on 2022-11-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='team',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
