# Generated by Django 4.1.2 on 2022-11-03 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='iee_id',
            new_name='ieee_id',
        ),
    ]
