# Generated by Django 4.2.2 on 2024-01-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_ip_address',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
