# Generated by Django 4.1.2 on 2022-11-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_members_position_members_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='gender',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
