# Generated by Django 4.1.2 on 2022-11-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_members_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='session',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='email_ieee',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
