# Generated by Django 4.1.2 on 2022-11-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_members_session_alter_members_email_ieee'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='renewal_time_stamp',
            field=models.DateField(blank=True, null=True),
        ),
    ]
