# Generated by Django 4.2.2 on 2024-01-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_ip_address_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='is_active_member',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='nsu_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
