# Generated by Django 4.2.2 on 2024-01-11 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_members_is_active_member_alter_members_nsu_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumni_members',
            options={'verbose_name': 'Alumni Members'},
        ),
    ]
