# Generated by Django 4.1.2 on 2022-12-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_members_renewal_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='position',
            field=models.IntegerField(default=13),
        ),
    ]
