# Generated by Django 4.1.2 on 2022-12-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_members_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='major',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
