# Generated by Django 4.2.2 on 2024-01-12 20:56

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_alumni_members_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni_members',
            name='picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='user_profile_pictures/default_profile_picture.png', force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='panel_profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='members',
            name='user_profile_picture',
            field=django_resized.forms.ResizedImageField(crop=None, default='user_profile_pictures/default_profile_picture.png', force_format=None, keep_meta=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='user_profile_pictures/'),
        ),
    ]
