# Generated by Django 4.1.2 on 2022-12-09 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0002_roles_and_position'),
        ('users', '0007_members_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='position',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='port.roles_and_position'),
        ),
    ]
