# Generated by Django 4.2.2 on 2024-01-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_panel_members_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='user_profile_picture',
            field=models.ImageField(default='user_profile_pictures/default_profile_picture.png', upload_to='user_profile_pictures/'),
        ),
    ]
