# Generated by Django 4.1.2 on 2022-12-09 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0002_roles_and_position'),
        ('users', '0008_alter_members_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='port.teams'),
        ),
    ]
