# Generated by Django 4.2.2 on 2024-01-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_members_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='user_profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile_pictures/'),
        ),
    ]
