# Generated by Django 4.1.2 on 2022-12-09 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0015_alter_recruited_members_recruitment_time'),
        ('users', '0009_alter_members_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.recruitment_session'),
        ),
    ]
