# Generated by Django 4.1.2 on 2022-12-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_members_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='renewal_time_stamp',
        ),
        migrations.AddField(
            model_name='members',
            name='joining_session',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='last_renewal',
            field=models.DateField(blank=True, null=True),
        ),
    ]
