# Generated by Django 4.1.2 on 2022-12-15 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_members_renewal_time_stamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='joining_session',
        ),
    ]
