# Generated by Django 4.2.2 on 2024-01-15 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_members_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='members',
            options={'ordering': ['position__rank'], 'verbose_name': 'INSB Registered Members'},
        ),
    ]
