# Generated by Django 4.0.5 on 2022-12-19 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_access_criterias_data_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_access',
            name='criteria',
        ),
        migrations.RemoveField(
            model_name='data_access',
            name='ieee_id',
        ),
        migrations.RemoveField(
            model_name='data_access',
            name='team',
        ),
        migrations.DeleteModel(
            name='Access_Criterias',
        ),
        migrations.DeleteModel(
            name='Data_Access',
        ),
    ]
