# Generated by Django 4.0.5 on 2022-12-31 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_data_access_criteria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='position',
        ),
    ]
