# Generated by Django 4.0.5 on 2022-12-31 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0002_roles_and_position'),
        ('users', '0015_remove_members_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='position',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='port.roles_and_position'),
        ),
    ]
