# Generated by Django 4.2.2 on 2024-01-21 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_usersignuptokentable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignuptokentable',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.members'),
        ),
    ]
