# Generated by Django 4.2.2 on 2024-02-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_usersignuptokentable_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_ip_address',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
