# Generated by Django 4.2.2 on 2024-02-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_user_ip_address_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
