# Generated by Django 4.0.5 on 2023-01-04 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_members_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='user_profile_picture',
        ),
    ]
