# Generated by Django 4.2.2 on 2024-02-09 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0014_volunteerawards'),
        ('users', '0020_members_is_blocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerAwardRecievers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributions', models.CharField(blank=True, max_length=600, null=True)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='port.volunteerawards')),
                ('award_reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.members')),
            ],
            options={
                'verbose_name': 'Award Recievers',
            },
        ),
    ]
