# Generated by Django 4.2.2 on 2024-02-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_volunteerawardrecievers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_ip_address',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
