# Generated by Django 4.2.2 on 2024-02-25 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_user_ip_address_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillSetTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_type', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Skill set Types',
            },
        ),
        migrations.CreateModel(
            name='MemberSkillSets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.members')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.skillsettypes')),
            ],
            options={
                'verbose_name': 'Member Skill Sets',
            },
        ),
    ]
