# Generated by Django 4.0.5 on 2023-01-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_members_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='linkedin_url',
            field=models.URLField(null=True),
        ),
    ]
