# Generated by Django 4.0.5 on 2023-01-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_members_linkedin_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='user_profile_picture',
            field=models.ImageField(default='user_profile_pictures/default_profile_picture.png', upload_to='user_profile_pictures/'),
        ),
    ]
