# Generated by Django 4.2.2 on 2024-02-28 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_memberskillsets_skill_delete_skillsettypes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberskillsets',
            name='skill',
        ),
    ]
