# Generated by Django 4.2.2 on 2024-02-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0015_skillsettypes'),
        ('users', '0025_remove_memberskillsets_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberskillsets',
            name='skill',
            field=models.ManyToManyField(blank=True, to='port.skillsettypes'),
        ),
    ]
