# Generated by Django 4.0.5 on 2023-01-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_members_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
