# Generated by Django 4.2.2 on 2024-02-29 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_memberskillsets_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberskillsets',
            old_name='skill',
            new_name='skills',
        ),
    ]
