# Generated by Django 4.0.5 on 2023-01-08 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership_development_team', '0012_remove_renewal_requests_encrypt_key'),
        ('users', '0027_alter_members_linkedin_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='last_renewal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membership_development_team.renewal_sessions'),
        ),
    ]
