# Generated by Django 4.2.2 on 2024-03-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_rename_skill_memberskillsets_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='completed_task_points',
            field=models.IntegerField(default=0),
        ),
    ]
