# Generated by Django 4.2.2 on 2024-03-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_rename_skill_memberskillsets_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni_members',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
