# Generated by Django 3.2.16 on 2023-01-31 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_members_last_renewal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='last_renewal',
        ),
        migrations.AddField(
            model_name='members',
            name='last_renewal_session',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='last_renewal_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
