# Generated by Django 4.2.2 on 2024-04-07 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_alumni_members_email'),
        ('users', '0029_alter_members_completed_task_points'),
    ]

    operations = [
    ]
