# Generated by Django 4.2.2 on 2024-05-31 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_merge_20240330_0052'),
        ('users', '0030_merge_20240407_1652'),
    ]

    operations = [
    ]
