# Generated by Django 3.2.16 on 2023-03-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20230223_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='email_nsu',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='email_personal',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
