# Generated by Django 4.2.2 on 2023-07-15 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0004_alter_chapters_society_and_affinity_groups_options_and_more'),
        ('users', '0032_auto_20230305_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ex_panel_members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, default='user_profile_pictures/default_profile_picture.png', null=True, upload_to='panel_profile_pictures/')),
                ('linkedin_link', models.URLField(blank=True, max_length=100, null=True)),
                ('facebook_link', models.URLField(blank=True, max_length=100, null=True)),
                ('mail', models.URLField(blank=True, max_length=50, null=True)),
                ('ieee_collaboratec', models.URLField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Ex Panel Members',
            },
        ),
        migrations.CreateModel(
            name='Executive_commitee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=40)),
                ('current', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Executive Commitees',
            },
        ),
        migrations.CreateModel(
            name='Executive_commitee_members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.ex_panel_members')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.members')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='port.roles_and_position')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.executive_commitee')),
            ],
            options={
                'verbose_name': 'Executive Commitee Members',
            },
        ),
    ]
