# Generated by Django 4.2.2 on 2023-08-21 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 8, 21, 19, 10, 47, 969372)),
        ),
    ]
