# Generated by Django 4.2.2 on 2023-08-24 16:09

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_alter_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='user_profile_picture',
            field=django_resized.forms.ResizedImageField(crop=None, default='user_profile_pictures/default_profile_picture.png', force_format='JPEG', keep_meta=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='user_profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
