# Generated by Django 4.2.2 on 2023-08-27 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_alter_user_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Visitors on Main Website'},
        ),
    ]
