# Generated by Django 4.2.2 on 2023-10-29 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0020_panels'),
        ('users', '0045_remove_members_panel_session_panel_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel_members',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='port.teams'),
        ),
    ]
