# Generated by Django 4.2.2 on 2023-10-29 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_panel_members_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='panel_members',
            options={'verbose_name': 'Panel Members (Whole Tenure)'},
        ),
    ]
