# Generated by Django 4.2.2 on 2023-11-19 08:03

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_ex_panel_members_contact_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni_Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', django_resized.forms.ResizedImageField(blank=True, crop=None, default='user_profile_pictures/default_profile_picture.png', force_format='JPEG', keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='panel_profile_pictures/')),
                ('linkedin_link', models.URLField(blank=True, max_length=100, null=True)),
                ('facebook_link', models.URLField(blank=True, max_length=100, null=True)),
                ('email', models.URLField(blank=True, max_length=50, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=50, null=True)),
                ('ieee_collaboratec', models.URLField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Ex Panel Members',
            },
        ),
        migrations.AlterField(
            model_name='panel_members',
            name='ex_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.alumni_members'),
        ),
        migrations.DeleteModel(
            name='Ex_panel_members',
        ),
    ]
