# Generated by Django 4.2.2 on 2023-12-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_alumni_members_alter_panel_members_ex_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='is_active_member',
            field=models.BooleanField(default=False),
        ),
    ]
