# Generated by Django 4.2.2 on 2023-12-30 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_alter_user_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_IP_Address',
        ),
    ]
