# Generated by Django 4.2.2 on 2023-12-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_rename_user_user_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='ieee_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='members',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='nsu_id',
            field=models.BigIntegerField(),
        ),
    ]
