# Generated by Django 3.2.16 on 2023-01-30 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('port', '0004_alter_chapters_society_and_affinity_groups_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='team_meeting_minutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_title', models.CharField(max_length=150)),
                ('meeting_date', models.DateField(blank=True, null=True)),
                ('meeting_venue', models.CharField(max_length=150)),
                ('meeting_present', models.CharField(max_length=150)),
                ('meeting_excused', models.CharField(max_length=150)),
                ('meeting_absent', models.CharField(max_length=150)),
                ('meeting_called_by', models.CharField(max_length=150)),
                ('meeting_agendas', models.CharField(max_length=150)),
                ('meeting_approval', models.CharField(max_length=150)),
                ('meeting_discussion', models.CharField(max_length=3000)),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='port.teams')),
            ],
            options={
                'verbose_name': 'Registered Team Meetings',
            },
        ),
    ]
