# Generated by Django 3.2.16 on 2023-01-30 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0004_alter_chapters_society_and_affinity_groups_options_and_more'),
        ('meeting_minutes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team_meeting_minutes',
            options={},
        ),
        migrations.AddField(
            model_name='team_meeting_minutes',
            name='meeting_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='branch_meeting_minutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_title', models.CharField(max_length=150)),
                ('meeting_date', models.DateField(blank=True, null=True)),
                ('meeting_time', models.TimeField(blank=True, null=True)),
                ('meeting_venue', models.CharField(max_length=150)),
                ('meeting_present', models.CharField(max_length=150)),
                ('meeting_excused', models.CharField(max_length=150)),
                ('meeting_absent', models.CharField(max_length=150)),
                ('meeting_called_by', models.CharField(max_length=150)),
                ('meeting_agendas', models.CharField(max_length=150)),
                ('meeting_approval', models.CharField(max_length=150)),
                ('meeting_discussion', models.CharField(max_length=3000)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='port.chapters_society_and_affinity_groups')),
            ],
            options={
                'verbose_name': 'Registered Team Meetings',
            },
        ),
    ]
