# Generated by Django 3.2.16 on 2023-01-31 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_minutes', '0002_auto_20230130_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch_meeting_minutes',
            options={'verbose_name': 'Branch - Society Meeting'},
        ),
        migrations.AlterModelOptions(
            name='team_meeting_minutes',
            options={'verbose_name': 'Registered Team Meeting'},
        ),
        migrations.RenameField(
            model_name='branch_meeting_minutes',
            old_name='branch_id',
            new_name='branch_or_society_id',
        ),
    ]
