# Generated by Django 4.2.2 on 2023-11-28 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0025_roles_and_position_is_mentor'),
        ('chapters_and_affinity_group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sc_ag_members',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='port.roles_and_position'),
        ),
        migrations.AlterField(
            model_name='sc_ag_members',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='port.teams'),
        ),
    ]
