# Generated by Django 4.2.2 on 2023-12-05 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapters_and_affinity_group', '0003_gg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GG',
        ),
    ]
