from smtplib import SMTPException
import socket
from django.conf import settings
from system_administration.render_access import Access_Render
from django.core.mail import send_mail
from . import renderData
from users.models import Members

def send_emails_to_officials_upon_site_registration_request(request,name,ieee_id,position,team_name,official_name,recipent):
    '''This email function sends email to mdt officials upon a form submission on portal site registration'''
    
    try:
            # Send an Email now
            subject = "New Portal Registration Request"
            # Getting the site domain
            site_domain = request.META['HTTP_HOST']
            message = f"Dear {official_name},\nYou have recieved a new portal registration request by\nName: {name}\nIEEE ID: {ieee_id}\nTeam:{team_name}\nPosition:{position}\n\nTo verify/approve this request, please follow the link below:\n{site_domain}/portal/membership_development_team/insb_members/site_registration/request_details/{request.POST['ieee_id']}\n\nThis email notification was auto generated by the Portal Website of INSB. If you are not responsible for this particular task, please contact the system admin of IEE NSU SB portal website.\nThank you."
            email_from = settings.EMAIL_HOST_USER
            recipient_list = [recipent]
            send_mail(
                subject, message, email_from, recipient_list
            )
            return True
    except SMTPException as e:
        return False

def send_email_on_site_registration_verification_to_user(request,new_member_name,new_member_personal_mail):
    
    '''This email function send email to user upon Form verification'''
    
    try:
        #Send an Email now
        subject="Site Registration Request Approved"
        #Getting the site domain
        site_domain=request.META['HTTP_HOST']
        message=f"Dear {new_member_name}, Welcome aboard!\nYour request to join IEEE NSU SB's Portal has been Approved! Please redirect to the site to Signup With your IEEE ID using this link: {site_domain}/portal/users/signup\nThank You."
        email_from=settings.EMAIL_HOST_USER
        recipient_list=[new_member_personal_mail,]
        send_mail(
                subject,message,email_from,recipient_list
        )
        return True
    except SMTPException as e:
        return False
    
def send_email_to_recruitees_upon_recruitment(name,nsu_id,recruited_member_email,recruitment_session):
    '''This function sends email to the newly recruited members to confirm their membership'''
    try:
        subject="Recruitment Successful"
        
        load_mdt_co_ordinator=Members.objects.filter(team=12,position=9)
        
        message_header=f"Dear {name},\n"
        message_body=f"I would like to wish a warm welcome to you at the IEEE NSU Student Branch for the {recruitment_session} Session. Your Recruitment process is successful, and I also can't wait to see how well you all work together. This is to make sure that the organization is running smoothly and all of our members are enjoying and learning from their volunteer experiences.\nMoreover, please join the IEEE NSU Student Branch Facebook Group:\nhttps://www.facebook.com/groups/ieeensusb/ \n\nKeep in touch for our next updates. Best of luck!"
        message_footer=f"\n\nRegards,\n{load_mdt_co_ordinator[0].name}\nMembership Development Coordiantor,\nIEE NSU Student Branch\n{load_mdt_co_ordinator[0].email_ieee} | {load_mdt_co_ordinator[0].email_personal}\nFacebook: {load_mdt_co_ordinator[0].facebook_url}\nContact: {load_mdt_co_ordinator[0].contact_no}"
        message_footer2="\n\nThis e-mail was automatically generated by the portal website of IEEE NSU Student Branch. If you were not supposed to recieve this e-mail, contact our Membership Development Team to resolve this issue.\nThank you!"
        message=message_header+message_body+message_footer+message_footer2
        
        email_from=settings.EMAIL_HOST_USER
        recipient_list=[recruited_member_email]
        send_mail(
            subject,message,email_from,recipient_list
        )
        return True
    except:
        return False
    
def send_emails_upon_filling_up_renewal_form(ieee_id,reciever_name,reciever_email,renewal_session,renewal_check_dict,request_id,form_id):
    '''This function sends email to users upon filling up the renewal form'''
    
    try:
        renewal_list,total_amount=renderData.MDT_DATA.process_renewal_item_dict(renewal_check_dict=renewal_check_dict,request_id=request_id,form_id=form_id)
        seperator=", "
        
        load_mdt_co_ordinator=renderData.MDT_DATA.load_MDT_coordinator()
        
        subject="CONFIRMATION - Renewal Application Recieved!"
        
        message_body=f"""Dear {reciever_name},\n
Greetings from IEEE NSU Student Branch. We hope this mail finds you well and in high spirits. Thank you for taking the time to complete the membership renewal form of IEEE NSU Student Branch. Your commitment to renewing your membership is greatly appreciated and we are thrilled to have you continue as a valued member.\n
You have applied for {seperator.join(renewal_list)} in the {renewal_session} session with the IEEE Membership ID: {ieee_id}. Total amount you paid was {total_amount} BDT.\n
Your renewed membership ensures that you’ll continue to enjoy the benefits of being part of IEEE and IEEE NSU Student Branch including IEEEXplore, Spectrum, R10 Newsletter and more. Upon the completion of the form as the first step, we now are confident to proceed to the payment procedures and relevant works. Please keep an eye on your IEEE mail on your membership renewal confirmation and stay connected.\n
Once again, we appreciate you renewing your membership once more. We are grateful that you are a member of our community and are looking forward to an amazing new year with you."""
        
        message_footer=f"\n\nRegards,\n{load_mdt_co_ordinator[0].name}\nMembership Development Coordiantor,\nIEE NSU Student Branch\n{load_mdt_co_ordinator[0].email_ieee} | {load_mdt_co_ordinator[0].email_personal}\nFacebook: {load_mdt_co_ordinator[0].facebook_url}\nContact: {load_mdt_co_ordinator[0].contact_no}"
        message_footer2="\n\nThis e-mail was automatically generated by IEEE NSU Student Branch Portal. If you were not supposed to recieve this e-mail, contact our Membership Development Team to resolve this issue.\nThank you!"
        message=message_body+message_footer+message_footer2
        
        email_from=settings.EMAIL_HOST_USER
        recipient_list=[reciever_email]
        send_mail(
            subject,message,email_from,recipient_list
        )
        return True
    except:
        return False

def send_email_upon_renewal_confirmed(reciever_name,reciever_email):
    '''This function sends email to users upon the renewal is done'''
    try:
        
        load_mdt_co_ordinator=renderData.MDT_DATA.load_MDT_coordinator()
        
        subject="SUCCESS - Membership Renewal Complete."
        
        message_body=f"""Dear {reciever_name},\n
Greetings from IEEE NSU Student Branch. Hope this mail finds you well and in high spirits. This mail is to confirm that your payment procedure is completed and your IEEE membership has been renewed. Thank you for renewing your membership and we are thrilled to have you continue as a valued member.\n
The payment of your membership renewal grants you access to digital products and upon the renewal of IEEE membership, you will continue to enjoy the benefits of being part of IEEE and IEEE NSU Student Branch including IEEEXplore, Spectrum, R10 Newsletter and more.  We hope you will have an amazing year ahead with IEEE and IEEE NSU Student Branch. Stay connected and build your network and share your experience in IEEE Membership Forum on IEEE Collabratec.\n
We appreciate you renewing your membership and expect to take the best advantage and benefits. Looking forward to an amazing new year with you."""
        message_footer=f"\n\nRegards,\n{load_mdt_co_ordinator[0].name}\nMembership Development Coordiantor,\nIEE NSU Student Branch\n{load_mdt_co_ordinator[0].email_ieee} | {load_mdt_co_ordinator[0].email_personal}\nFacebook: {load_mdt_co_ordinator[0].facebook_url}\nContact: {load_mdt_co_ordinator[0].contact_no}"
        message_footer2="\n\nThis e-mail was automatically generated by IEEE NSU Student Branch Portal. If you were not supposed to recieve this e-mail, contact our Membership Development Team to resolve this issue.\nThank you!"
        message=message_body+message_footer+message_footer2
        email_from=settings.EMAIL_HOST_USER
        recipient_list=[reciever_email]
        send_mail(
                subject,message,email_from,recipient_list
            )
        return True
    except:
        return False
