# Generated by Django 4.2.2 on 2023-12-13 13:57

import ckeditor.fields
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('central_events', '0017_events_form_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content_Team_Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='Content team documents'), upload_to='')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central_events.events')),
            ],
            options={
                'verbose_name': 'Content Team Document',
            },
        ),
        migrations.CreateModel(
            name='Content_Caption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central_events.events')),
            ],
            options={
                'verbose_name': 'Content Team Caption ',
            },
        ),
    ]
