# Generated by Django 4.2.2 on 2023-12-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_writing_and_publications_team', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content_caption',
            options={'verbose_name': 'Content Team Caption'},
        ),
        migrations.AddField(
            model_name='content_caption',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
