# Generated by Django 4.2.2 on 2024-01-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_writing_and_publications_team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content_team_document',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='Content_Team_Documents/'),
        ),
    ]
