# Generated by Django 4.2.2 on 2023-12-20 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_writing_and_publications_team', '0002_alter_content_caption_options_content_caption_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content_caption',
            old_name='caption',
            new_name='notes',
        ),
    ]
