# Generated by Django 4.2.2 on 2024-02-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_writing_and_publications_team', '0003_content_team_content_content_team_content_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content_team_content',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
