# Generated by Django 4.2.2 on 2023-12-20 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_events', '0017_events_form_link'),
        ('content_writing_and_publications_team', '0003_rename_caption_content_caption_notes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Content_Caption',
            new_name='Content_Notes',
        ),
    ]
