# Generated by Django 4.2.2 on 2023-12-20 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_writing_and_publications_team', '0004_rename_content_caption_content_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content_notes',
            options={'verbose_name': 'Content Team Notes'},
        ),
    ]
