# Generated by Django 4.2.2 on 2023-12-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_writing_and_publications_team', '0005_alter_content_notes_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content_notes',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
