# Generated by Django 4.2.2 on 2023-12-20 15:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_writing_and_publications_team', '0006_alter_content_notes_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content_notes',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
