# Generated by Django 4.2.2 on 2023-12-21 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('central_events', '0017_events_form_link'),
        ('content_writing_and_publications_team', '0007_alter_content_notes_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content_Team_Documents_Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documents_link', models.URLField(blank=True, max_length=300, null=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central_events.events')),
            ],
            options={
                'verbose_name': 'Content Team Documents Link',
            },
        ),
    ]
