# Generated by Django 4.2.2 on 2023-12-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_writing_and_publications_team', '0008_content_team_documents_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content_team_document',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='Content Team Documents/'),
        ),
    ]
