# Generated by Django 4.2.2 on 2023-12-23 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_writing_and_publications_team', '0009_alter_content_team_document_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content_notes',
            options={'verbose_name': 'Content Team Captions'},
        ),
        migrations.RenameField(
            model_name='content_notes',
            old_name='notes',
            new_name='caption',
        ),
    ]
