# Generated by Django 3.2.16 on 2023-03-07 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('central_branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='central_branch.event_type'),
        ),
    ]
