# Generated by Django 4.2.2 on 2024-09-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_branch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_draft',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Sent', 'Sent'), ('Paused', 'Paused'), ('Failed', 'Failed'), ('Unknown', 'Unknown')], default='Unknown'),
        ),
    ]
