# Generated by Django 4.2.2 on 2023-06-22 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_branch', '0002_auto_20230308_0046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event_type',
            options={'verbose_name': 'Event Type'},
        ),
    ]
