# Generated by Django 4.2.2 on 2024-09-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_branch', '0002_email_draft_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_draft',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Sent', 'Sent'), ('Paused', 'Paused'), ('Failed', 'Failed'), ('Unknown', 'Unknown')], default='Unknown', max_length=100),
        ),
    ]
