# Generated by Django 4.2.2 on 2024-09-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_branch', '0003_alter_email_draft_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_draft',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Sent', 'Sent'), ('Paused', 'Paused'), ('Failed', 'Failed'), ('None', 'None')], default=None, max_length=100),
        ),
    ]
