# Generated by Django 4.2.2 on 2023-07-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_branch', '0004_events_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
