# Generated by Django 4.2.2 on 2023-07-14 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_branch', '0004_events_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='slug',
        ),
    ]
