# Generated by Django 4.2.2 on 2023-07-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_branch', '0005_remove_events_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='flagship_event',
            field=models.BooleanField(default=False),
        ),
    ]
