# Generated by Django 4.2.2 on 2023-07-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_branch', '0005_alter_events_event_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=500)),
                ('Research_picture', models.ImageField(blank=True, default='Central Branch/Research_pictures/default_research_picture.png', null=True, upload_to='Central Branch/Research_pictures/')),
                ('Author_names', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Research Paper',
            },
        ),
    ]
