# Generated by Django 4.2.2 on 2023-07-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_branch', '0006_researchpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpaper',
            name='Publication_link',
            field=models.URLField(default=False),
        ),
    ]
