# Generated by Django 4.2.2 on 2023-07-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_branch', '0006_events_flagship_event'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='events',
        #     name='publish_in_main_web',
        #     field=models.BooleanField(default=False),
        # ),
    ]
