# Generated by Django 4.2.2 on 2023-07-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_branch', '0007_researchpaper_publication_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpaper',
            name='Publication_link',
            field=models.URLField(),
        ),
    ]
