# Generated by Django 4.2.2 on 2023-07-13 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0004_alter_chapters_society_and_affinity_groups_options_and_more'),
        ('central_branch', '0008_alter_researchpaper_publication_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=500)),
                ('Date', models.DateField()),
                ('Category', models.CharField(blank=True, max_length=300, null=True)),
                ('Publisher', models.CharField(max_length=160)),
                ('Society_Affinity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='port.chapters_society_and_affinity_groups')),
            ],
        ),
    ]
