# Generated by Django 4.2.2 on 2023-10-29 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_branch', '0009_executive_commitee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Executive_commitee',
        ),
    ]
