# Generated by Django 4.2.2 on 2023-07-13 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_branch', '0009_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Blog'},
        ),
    ]
