# Generated by Django 4.2.2 on 2023-11-28 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_branch', '0010_delete_executive_commitee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='event_type',
        ),
        migrations.DeleteModel(
            name='Event_type',
        ),
    ]
