# Generated by Django 4.2.2 on 2023-07-13 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0005_blogcategory'),
        ('central_branch', '0011_alter_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Society_Affinity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='port.chapters_society_and_affinity_groups'),
        ),
    ]
