# Generated by Django 4.2.2 on 2023-11-27 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_branch', '0011_remove_events_event_type_delete_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='type_of_event',
        ),
        # migrations.DeleteModel(
        #     name='Type_of_Event',
        # ),
    ]
