# Generated by Django 4.2.2 on 2023-07-13 13:02

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_branch', '0012_alter_blog_society_affinity'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='Title', unique=True),
        ),
    ]
