# Generated by Django 4.2.2 on 2023-11-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_branch', '0013_type_of_event_events_type_of_event'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Event_Category',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('event_category', models.CharField(max_length=60)),
        #     ],
        #     options={
        #         'verbose_name': 'Event Category',
        #     },
        # ),
        # migrations.RemoveField(
        #     model_name='events',
        #     name='type_of_event',
        # ),
        # migrations.DeleteModel(
        #     name='Type_of_Event',
        # ),
    ]
