# Generated by Django 4.2.2 on 2023-07-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_branch', '0013_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Blog_picture',
            field=models.ImageField(blank=True, default='Central Branch/Blog_pictures/default_blog_picture.png', null=True, upload_to='Central Branch/Blog_pictures/'),
        ),
    ]
