# Generated by Django 4.2.2 on 2023-07-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_branch', '0014_blog_blog_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Blog_picture',
            field=models.ImageField(blank=True, default='Central Branch/Blog_pictures/default_blog_picture.png', null=True, upload_to='Central Branch/Blog_pictures'),
        ),
    ]
