# Generated by Django 4.2.2 on 2023-12-06 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_branch', '0015_delete_event_category_remove_event_proposal_event_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media_links',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='media_selected_images',
            name='event_id',
        ),
        migrations.DeleteModel(
            name='Event_Logistic_Items',
        ),
        migrations.DeleteModel(
            name='Media_Links',
        ),
        migrations.DeleteModel(
            name='Media_Selected_Images',
        ),
    ]
