# Generated by Django 4.2.2 on 2023-12-06 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_branch', '0016_remove_media_links_event_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphics_links',
            name='event_id',
        ),
        migrations.DeleteModel(
            name='Graphics_Files',
        ),
        migrations.DeleteModel(
            name='Graphics_Links',
        ),
    ]
