# Generated by Django 4.2.2 on 2023-12-30 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_branch', '0017_remove_graphics_links_event_id_delete_graphics_files_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_permission',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='event_permission',
            name='permission_id',
        ),
        migrations.RemoveField(
            model_name='event_proposal',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='event_venue',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='event_venue',
            name='venue_id',
        ),
        migrations.RemoveField(
            model_name='events',
            name='event_organiser',
        ),
        migrations.RemoveField(
            model_name='events',
            name='super_event_name',
        ),
        migrations.RemoveField(
            model_name='interbranchcollaborations',
            name='collaboration_with',
        ),
        migrations.RemoveField(
            model_name='interbranchcollaborations',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='intrabranchcollaborations',
            name='event_id',
        ),
        migrations.DeleteModel(
            name='Type_of_Event',
        ),
        migrations.DeleteModel(
            name='Event_Permission',
        ),
        migrations.DeleteModel(
            name='Event_Proposal',
        ),
        migrations.DeleteModel(
            name='Event_Venue',
        ),
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.DeleteModel(
            name='InterBranchCollaborations',
        ),
        migrations.DeleteModel(
            name='IntraBranchCollaborations',
        ),
        migrations.DeleteModel(
            name='SuperEvents',
        ),
    ]
