# Generated by Django 4.2.2 on 2023-07-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_branch', '0017_alter_blog_blog_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Blog_picture',
            field=models.ImageField(blank=True, default='media_files/Central_Branch/Blog_pictures/default_blog_picture.png', null=True, upload_to='media_files/Central_Branch/Blog_pictures/'),
        ),
    ]
