# Generated by Django 4.2.2 on 2023-07-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_branch', '0019_alter_blog_blog_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Description',
            field=models.TextField(default='None', max_length=5000),
        ),
    ]
