# Generated by Django 4.2.2 on 2023-07-14 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_branch', '0020_blog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Blog_picture',
            field=models.ImageField(blank=True, default='User Files/Central_Branch/Blog_pictures/default_blog_picture.png', null=True, upload_to='User Files/Central_Branch/Blog_pictures/'),
        ),
    ]
