# Generated by Django 4.1.2 on 2022-11-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='recruited_members',
            fields=[
                ('nsu_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ieee_id', models.IntegerField(null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=15, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('email_personal', models.EmailField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=8, null=True)),
                ('facebook_url', models.CharField(blank=True, max_length=100, null=True)),
                ('home_address', models.CharField(blank=True, max_length=50, null=True)),
                ('major', models.CharField(blank=True, max_length=30, null=True)),
                ('graduating_year', models.IntegerField(blank=True, null=True)),
                ('recruitment_time', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.IntegerField(blank=True)),
                ('payment_status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Recruited Members',
            },
        ),
    ]
