# Generated by Django 4.1.2 on 2022-11-15 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_recruited_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruited_members',
            name='ieee_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
