# Generated by Django 4.2.2 on 2024-02-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0015_skillsettypes'),
        ('recruitment', '0002_recruited_members_unique_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruited_members',
            name='skills',
            field=models.ManyToManyField(blank=True, to='port.skillsettypes'),
        ),
    ]
