# Generated by Django 4.1.2 on 2022-11-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_alter_recruited_members_ieee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruited_members',
            old_name='payment_status',
            new_name='ieee_payment_status',
        ),
        migrations.AddField(
            model_name='recruited_members',
            name='cash_payment_satatus',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='recruited_members',
            name='recruited_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
