# Generated by Django 4.2.2 on 2024-08-18 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_recruited_members_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruited_members',
            name='blood_group',
            field=models.CharField(blank=True, default='None', max_length=10, null=True),
        ),
    ]
