# Generated by Django 4.1.2 on 2022-11-20 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_rename_payment_status_recruited_members_ieee_payment_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruited_members',
            old_name='cash_payment_satatus',
            new_name='cash_payment_status',
        ),
    ]
