# Generated by Django 4.2.2 on 2024-09-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_recruited_members_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruited_members',
            name='department',
            field=models.CharField(blank=True, default='ECE', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='recruited_members',
            name='school',
            field=models.CharField(blank=True, default='SEPS', max_length=200, null=True),
        ),
    ]
