# Generated by Django 4.2.2 on 2024-09-15 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_recruited_members_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='nsu_school',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_full_name', models.CharField(max_length=200)),
                ('school_initial', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'NSU School of Degrees',
            },
        ),
        migrations.CreateModel(
            name='nsu_departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_full_name', models.CharField(max_length=200)),
                ('department_initial', models.CharField(max_length=20)),
                ('department_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.nsu_school')),
            ],
            options={
                'verbose_name': 'NSU Departments',
            },
        ),
    ]
