# Generated by Django 4.1.2 on 2022-11-25 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_rename_cash_payment_satatus_recruited_members_cash_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruited_members',
            name='ieee_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
