# Generated by Django 4.2.2 on 2024-09-15 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_nsu_school_nsu_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='nsu_majors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_full_name', models.CharField(max_length=200)),
                ('major_initial', models.CharField(max_length=20)),
                ('major_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.nsu_departments')),
            ],
            options={
                'verbose_name': 'NSU Majors',
            },
        ),
    ]
