# Generated by Django 4.1.2 on 2022-11-27 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_alter_recruited_members_recruitment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruited_members',
            name='recruitment_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 27, 22, 16, 14, 749564), null=True),
        ),
    ]
