# Generated by Django 4.1.2 on 2022-12-01 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0009_alter_recruited_members_recruitment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruited_members',
            name='recruitment_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 1, 22, 29, 43, 842787), null=True),
        ),
    ]
