# Generated by Django 4.1.2 on 2022-12-04 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0012_alter_recruited_members_recruitment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruited_members',
            name='recruitment_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 5, 1, 5, 50, 505958), null=True),
        ),
    ]
