# Generated by Django 4.1.2 on 2022-12-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0014_alter_recruited_members_recruitment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruited_members',
            name='recruitment_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
