# Generated by Django 4.0.5 on 2023-01-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0016_alter_recruited_members_home_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment_session',
            name='session_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
