# Generated by Django 4.0.5 on 2023-01-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0017_recruitment_session_session_time'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='recruited_members',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        #     preserve_default=False,
        # ),
        migrations.AlterField(
            model_name='recruited_members',
            name='nsu_id',
            field=models.IntegerField(),
        ),
    ]
