# Generated by Django 3.2.16 on 2023-02-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0019_auto_20230223_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruited_members',
            name='green_status',
        ),
        migrations.RemoveField(
            model_name='recruited_members',
            name='red_status',
        ),
        migrations.AddField(
            model_name='recruited_members',
            name='recruitee_status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
