# Generated by Django 3.2.16 on 2023-02-23 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0020_auto_20230223_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruited_members',
            name='recruitee_status',
        ),
        migrations.AddField(
            model_name='recruited_members',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
