# Generated by Django 3.2.16 on 2023-02-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0021_auto_20230223_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruited_members',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
