# Generated by Django 3.2.16 on 2023-03-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0022_alter_recruited_members_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruited_members',
            name='emergency_contact_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
