# Generated by Django 3.2.16 on 2023-03-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0023_recruited_members_emergency_contact_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruited_members',
            name='nsu_email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
