# Generated by Django 3.2.16 on 2023-03-05 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0024_recruited_members_nsu_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruited_members',
            old_name='nsu_email',
            new_name='email_nsu',
        ),
    ]
