# Generated by Django 4.2.2 on 2023-08-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0025_rename_nsu_email_recruited_members_email_nsu'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruited_members',
            name='facebook_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
