# Generated by Django 4.2.2 on 2023-12-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0026_recruited_members_facebook_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruited_members',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='recruited_members',
            name='nsu_id',
            field=models.BigIntegerField(),
        ),
    ]
