# Generated by Django 4.2.2 on 2023-12-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0027_alter_recruited_members_facebook_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruited_members',
            name='nsu_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
