# Generated by Django 4.2.2 on 2023-12-30 17:38

import ckeditor.fields
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ras_Query_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'RAS SBC Contact Form Queries',
            },
        ),
        migrations.CreateModel(
            name='Ras_Sbc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ras_banner_image', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/RAS/banner_picture')),
                ('about_ras', ckeditor.fields.RichTextField(max_length=2000)),
                ('mission_vision', ckeditor.fields.RichTextField(max_length=2000)),
                ('mission_vision_picture', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/RAS/mission_vision_picture')),
                ('what_is_ras', ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True)),
                ('why_join_ras', ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True)),
                ('what_activities', ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True)),
                ('how_to_join', ckeditor.fields.RichTextField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'RAS SBC Informations',
            },
        ),
    ]
