# Generated by Django 3.2.16 on 2023-10-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieee_nsu_sb_ras_sbc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ras_Query_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'RAS SBC Contact Form Queries',
            },
        ),
        migrations.AddField(
            model_name='ras_sbc',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ras_sbc',
            name='contact_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ras_sbc',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
