# Generated by Django 4.2.2 on 2023-10-21 08:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieee_nsu_sb_ras_sbc', '0002_auto_20231021_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ras_sbc',
            name='about_ras',
            field=ckeditor.fields.RichTextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='ras_sbc',
            name='how_to_join',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ras_sbc',
            name='mission_vision',
            field=ckeditor.fields.RichTextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='ras_sbc',
            name='what_activities',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ras_sbc',
            name='what_is_ras',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ras_sbc',
            name='why_join_ras',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
