# Generated by Django 4.2.2 on 2023-10-21 08:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ieee_nsu_sb_ras_sbc', '0003_alter_ras_sbc_about_ras_alter_ras_sbc_how_to_join_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ras_sbc',
            name='how_to_join',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ras_sbc',
            name='what_activities',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ras_sbc',
            name='what_is_ras',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ras_sbc',
            name='why_join_ras',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True),
        ),
    ]
