# Generated by Django 4.2.2 on 2024-02-20 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0022_alter_user_ip_address_created_at'),
        ('port', '0014_volunteerawards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('points', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Task Category',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('task_type', models.CharField(max_length=30)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('drive_link', models.TextField(blank=True, null=True)),
                ('has_file_upload', models.BooleanField(default=False)),
                ('has_content', models.BooleanField(default=False)),
                ('has_picture_upload', models.BooleanField(default=False)),
                ('has_permission_paper', models.BooleanField(default=False)),
                ('members', models.ManyToManyField(blank=True, to='users.members')),
                ('sc_ag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='port.chapters_society_and_affinity_groups')),
                ('task_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_assignation.task_category')),
                ('team', models.ManyToManyField(blank=True, to='port.teams')),
            ],
            options={
                'verbose_name': 'Task',
            },
        ),
    ]
