# Generated by Django 4.2.2 on 2024-02-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_assignation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='sc_ag_id',
            new_name='task_of',
        ),
        migrations.AddField(
            model_name='task',
            name='is_task_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('Team', 'Team'), ('Individuals', 'Individuals')], max_length=30),
        ),
    ]
