# Generated by Django 4.2.2 on 2024-02-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_user_ip_address_created_at'),
        ('task_assignation', '0002_rename_sc_ag_id_task_task_of_task_is_task_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='has_drive_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='team_coordinators',
            field=models.ManyToManyField(blank=True, related_name='team_coordinators', to='users.members'),
        ),
        migrations.AlterField(
            model_name='task',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='team_members', to='users.members'),
        ),
    ]
