# Generated by Django 4.2.2 on 2024-02-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_user_ip_address_created_at'),
        ('task_assignation', '0003_task_has_drive_link_task_team_coordinators_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='team_coordinators',
        ),
        migrations.AddField(
            model_name='task',
            name='task_created_by',
            field=models.CharField(default=123, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', to='users.members'),
        ),
    ]
