# Generated by Django 4.2.2 on 2024-02-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_assignation', '0004_remove_task_team_coordinators_task_task_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='has_others',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='others_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
