# Generated by Django 4.2.2 on 2024-02-24 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_assignation', '0006_remove_task_drive_link_task_media_task_drive_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='has_picture_upload',
            new_name='has_media',
        ),
    ]
