# Generated by Django 4.2.2 on 2024-02-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_assignation', '0008_task_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
