# Generated by Django 4.2.2 on 2024-02-25 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_assignation', '0009_alter_task_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task_history',
            old_name='task_history',
            new_name='task_history_details',
        ),
    ]
