# Generated by Django 4.2.2 on 2024-02-27 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_assignation', '0010_rename_task_history_task_history_task_history_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_log_details', models.JSONField()),
            ],
            options={
                'verbose_name': 'Task History',
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Task_History',
        ),
        migrations.AddField(
            model_name='task_log',
            name='task_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_assignation.task'),
        ),
    ]
