# Generated by Django 4.2.2 on 2024-02-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_assignation', '0012_alter_task_log_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_media',
            name='task_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
