# Generated by Django 4.2.2 on 2024-02-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_assignation', '0013_task_media_task_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_media',
            name='task_number',
        ),
        migrations.AddField(
            model_name='task_log',
            name='update_task_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
