# Generated by Django 4.2.2 on 2024-03-03 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_assignation', '0014_remove_task_media_task_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member_Task_Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.CharField(max_length=15)),
                ('points', models.IntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_assignation.task')),
            ],
            options={
                'verbose_name': 'Member Task Point',
            },
        ),
    ]
