# Generated by Django 4.2.2 on 2024-03-06 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0015_skillsettypes'),
        ('task_assignation', '0015_member_task_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member_task_point',
            old_name='points',
            new_name='completion_points',
        ),
        migrations.AddField(
            model_name='member_task_point',
            name='is_task_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Team_Task_Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_points', models.IntegerField(default=0)),
                ('is_task_completed', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_assignation.task')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='port.teams')),
            ],
            options={
                'verbose_name': 'Team Task Point',
            },
        ),
    ]
