# Generated by Django 4.2.2 on 2024-03-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_assignation', '0016_rename_points_member_task_point_completion_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_task_point',
            name='completion_points',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='task_category',
            name='points',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='team_task_point',
            name='completion_points',
            field=models.FloatField(default=0),
        ),
    ]
