# Generated by Django 4.2.2 on 2024-03-09 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_assignation', '0019_member_task_upload_types_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-deadline'], 'verbose_name': 'Task'},
        ),
    ]
