# Generated by Django 4.2.2 on 2024-03-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_assignation', '0021_permission_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission_paper',
            name='uploaded_by',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='task_content',
            name='uploaded_by',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='task_document',
            name='uploaded_by',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='task_drive_link',
            name='uploaded_by',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='task_media',
            name='uploaded_by',
            field=models.CharField(default='', max_length=50),
        ),
    ]
