# Generated by Django 4.2.2 on 2024-03-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_assignation', '0022_permission_paper_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member_task_point',
            name='comments',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
