# Generated by Django 4.2.2 on 2024-04-01 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_assignation', '0024_member_task_point_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='has_content',
        ),
        migrations.RemoveField(
            model_name='task',
            name='has_drive_link',
        ),
        migrations.RemoveField(
            model_name='task',
            name='has_file_upload',
        ),
        migrations.RemoveField(
            model_name='task',
            name='has_media',
        ),
        migrations.RemoveField(
            model_name='task',
            name='has_others',
        ),
        migrations.RemoveField(
            model_name='task',
            name='has_permission_paper',
        ),
    ]
