# Generated by Django 4.2.2 on 2024-04-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_assignation', '0025_remove_task_has_content_remove_task_has_drive_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member_task_upload_types',
            name='is_task_started_by_member',
            field=models.BooleanField(default=False),
        ),
    ]
