# Generated by Django 4.2.2 on 2024-05-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_assignation', '0027_team_task_forwarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_task_forwarded',
            name='task_forwarded_to_core_or_team_volunteers',
            field=models.BooleanField(default=False),
        ),
    ]
