# Generated by Django 4.2.2 on 2024-04-22 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_assignation', '0027_team_task_forward'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team_Task_Forward',
        ),
    ]
