# Generated by Django 4.2.2 on 2024-04-22 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0015_skillsettypes'),
        ('task_assignation', '0028_delete_team_task_forward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_Task_Forward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_forwarded', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_assignation.task')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='port.teams')),
            ],
            options={
                'verbose_name': 'Team Task Forwarded',
            },
        ),
    ]
