# Generated by Django 4.2.2 on 2024-05-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_assignation', '0029_team_task_forwarded_forwarded_by_for_volunteers'),
    ]

    operations = [
        migrations.AddField(
            model_name='member_task_point',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
