# Generated by Django 4.2.2 on 2024-04-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_assignation', '0029_team_task_forward'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_task_forward',
            name='forwared_by',
            field=models.CharField(default='', max_length=15),
        ),
    ]
