# Generated by Django 4.2.2 on 2024-05-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_assignation', '0030_team_task_forward_forwared_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team_task_forward',
            old_name='is_forwarded',
            new_name='is_forwarded_coordinator',
        ),
        migrations.AddField(
            model_name='team_task_forward',
            name='is_forwarded_incharge',
            field=models.BooleanField(default=False),
        ),
    ]
