# Generated by Django 4.2.2 on 2024-05-01 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_assignation', '0031_rename_is_forwarded_team_task_forward_is_forwarded_coordinator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team_task_forward',
            old_name='is_forwarded_coordinator',
            new_name='is_forwarded',
        ),
        migrations.RemoveField(
            model_name='team_task_forward',
            name='is_forwarded_incharge',
        ),
    ]
