# Generated by Django 4.2.2 on 2024-05-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_assignation', '0032_rename_is_forwarded_coordinator_team_task_forward_is_forwarded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_task_forward',
            name='is_forwarded_coordinator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team_task_forward',
            name='is_forwarded_incharge',
            field=models.BooleanField(default=False),
        ),
    ]
