# Generated by Django 4.2.2 on 2024-06-01 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotiificationTypes',
            new_name='NotificationTypes',
        ),
    ]
