# Generated by Django 4.2.2 on 2024-06-03 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_merge_20240531_1908'),
        ('notification', '0002_rename_notiificationtypes_notificationtypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtypes',
            name='type_icon',
            field=models.ImageField(blank=True, null=True, upload_to='notification_icons/'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.members'),
        ),
    ]
