# Generated by Django 4.2.2 on 2024-06-22 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notification', '0003_notificationtypes_type_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
