# Generated by Django 4.2.2 on 2024-07-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_pushnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
