# Generated by Django 4.2.2 on 2024-07-13 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('central_events', '0020_alter_google_calendar_attachments_file_url'),
        ('notification', '0007_alter_notifications_general_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='event',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='central_events.events'),
        ),
    ]
