# Generated by Django 4.2.2 on 2024-09-24 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0008_notifications_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
