# Generated by Django 4.2.2 on 2024-09-20 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0008_notifications_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 20, 21, 0, 52, 785371)),
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 20, 21, 0, 52, 785371)),
        ),
    ]
