# Generated by Django 4.2.2 on 2024-10-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0009_pushnotification_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='general_message',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
