# Generated by Django 4.2.2 on 2024-01-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
