# Generated by Django 4.2.2 on 2023-12-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('super_event_name', models.CharField(max_length=150)),
                ('super_event_description', models.CharField(blank=True, max_length=500, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Super Event',
            },
        ),
    ]
