# Generated by Django 4.2.2 on 2024-01-14 18:53

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0003_alter_roles_and_position_rank'),
        ('central_events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='superevents',
            options={'verbose_name': 'Mega Event'},
        ),
        migrations.AddField(
            model_name='superevents',
            name='banner_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='Mega Event Banner Images/'),
        ),
        migrations.AddField(
            model_name='superevents',
            name='mega_event_of',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='port.chapters_society_and_affinity_groups'),
        ),
    ]
