# Generated by Django 4.2.2 on 2024-01-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_events', '0002_events_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Feature this event'),
        ),
    ]
