# Generated by Django 4.2.2 on 2024-01-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_events', '0002_alter_superevents_options_superevents_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superevents',
            name='super_event_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
