# Generated by Django 4.2.2 on 2024-01-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_events', '0003_alter_events_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_time',
            field=models.CharField(blank=True, null=True),
        ),
    ]
