# Generated by Django 4.2.2 on 2023-12-06 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_and_operations_team', '0001_initial'),
        ('central_events', '0003_events_rename_event_categories_event_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media_Selected_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_image', models.ImageField(blank=True, default=None, null=True, upload_to='Event Selected Images/')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central_events.events')),
            ],
        ),
        migrations.CreateModel(
            name='Media_Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_link', models.URLField(blank=True, max_length=300, null=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central_events.events')),
            ],
        ),
        migrations.CreateModel(
            name='Event_Logistic_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buying_status', models.BooleanField(default=False)),
                ('spending_amount', models.FloatField(blank=True, null=True)),
                ('item_reciept', models.FileField(blank=True, null=True, upload_to='Logistic Reciepts/')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central_events.events')),
                ('logistic_item_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics_and_operations_team.logistic_item_list')),
            ],
        ),
    ]
