# Generated by Django 4.2.2 on 2024-01-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_events', '0004_events_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
