# Generated by Django 4.2.2 on 2024-01-18 05:43

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('central_events', '0004_superevents_publish_mega_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_logistic_items',
            name='item_reciept',
            field=models.FileField(blank=True, null=True, upload_to='Logistic_Reciepts/'),
        ),
        migrations.AlterField(
            model_name='graphics_files',
            name='graphics_file',
            field=models.FileField(blank=True, null=True, upload_to='Graphics_Items/'),
        ),
        migrations.AlterField(
            model_name='media_selected_images',
            name='selected_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='Event_Selected_Images/'),
        ),
        migrations.AlterField(
            model_name='superevents',
            name='banner_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='Mega_Event_Banner_Images/'),
        ),
    ]
