# Generated by Django 4.2.2 on 2023-12-06 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('central_events', '0005_graphics_links_graphics_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='central_events.event_category'),
        ),
    ]
