# Generated by Django 4.2.2 on 2024-02-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_events', '0006_events_end_date_events_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(blank=True, default='0000-00-00', null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_time',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
