# Generated by Django 4.2.2 on 2023-12-06 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0025_roles_and_position_is_mentor'),
        ('central_events', '0006_events_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_category',
            name='event_category_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='port.chapters_society_and_affinity_groups'),
        ),
    ]
