# Generated by Django 4.2.2 on 2024-02-17 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_events', '0007_alter_events_event_date_alter_events_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 2, 17, 18, 45, 34, 865975), null=True),
        ),
    ]
