# Generated by Django 4.2.2 on 2023-12-06 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_events', '0007_event_category_event_category_for'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='super_event_name',
            new_name='super_event_id',
        ),
    ]
