# Generated by Django 4.2.2 on 2023-12-08 20:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_events', '0009_alter_events_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
