# Generated by Django 4.2.2 on 2023-12-07 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('central_events', '0010_remove_events_event_type_events_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='event_type',
        ),
        migrations.AddField(
            model_name='events',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='central_events.event_category'),
        ),
    ]
