# Generated by Django 4.2.2 on 2023-12-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_events', '0012_remove_events_event_type_events_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_type',
            field=models.ManyToManyField(blank=True, to='central_events.event_category'),
        ),
    ]
