# Generated by Django 4.2.2 on 2023-12-09 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_events', '0010_alter_events_event_description'),
        ('central_events', '0013_alter_events_event_type'),
    ]

    operations = [
    ]
