# Generated by Django 4.2.2 on 2024-02-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_events', '0014_alter_events_registration_fee_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='registration_fee_amount',
            field=models.TextField(blank=True, default='Non-IEEE Member: 0 BDT\n\nIEEE Member: 0 BDT', null=True),
        ),
    ]
