# Generated by Django 4.2.2 on 2023-12-09 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_events', '0014_merge_20231209_2309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event_permission',
            options={'verbose_name': 'Event Permission'},
        ),
    ]
