# Generated by Django 4.2.2 on 2023-12-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_events', '0016_events_registration_fee_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='form_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
