# Generated by Django 4.2.2 on 2024-07-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_events', '0016_events_google_calendar_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='publish_in_google_calendar',
            field=models.BooleanField(default=False),
        ),
    ]
