# Generated by Django 4.2.2 on 2024-07-10 16:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_events', '0017_events_publish_in_google_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_description_for_gc',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
