# Generated by Django 4.2.2 on 2024-07-10 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('central_events', '0018_events_event_description_for_gc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Google_Calendar_Attachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=50)),
                ('file_name', models.CharField(max_length=100)),
                ('file_url', models.CharField(max_length=100)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='central_events.events')),
            ],
            options={
                'verbose_name': 'Google Calendar Attachments',
            },
        ),
    ]
