# Generated by Django 4.2.2 on 2024-07-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_events', '0019_google_calendar_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='google_calendar_attachments',
            name='file_url',
            field=models.CharField(max_length=200),
        ),
    ]
