# Generated by Django 4.2.2 on 2024-07-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_events', '0020_alter_google_calendar_attachments_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='additional_attendees',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
