# Generated by Django 4.2.2 on 2024-07-12 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_events', '0022_alter_events_additional_attendees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='additional_attendees',
        ),
    ]
