# Generated by Django 4.2.2 on 2023-10-19 17:34

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('central_branch', '0008_rename_final_date_events_event_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graphics_Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graphics_link', models.URLField(blank=True, max_length=300, null=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central_branch.events')),
            ],
        ),
        migrations.CreateModel(
            name='Graphics_Banner_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_image', django_resized.forms.ResizedImageField(blank=True, crop=None, default=None, force_format='JPEG', keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='Event Banner Image/')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central_branch.events')),
            ],
        ),
    ]
