# Generated by Django 4.2.2 on 2024-01-13 00:04

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('graphics_team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphics_banner_image',
            name='selected_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='Event Banner Image/'),
        ),
    ]
