# Generated by Django 4.2.2 on 2024-01-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics_team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphics_banner_image',
            name='selected_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='Event Banner Image/'),
        ),
    ]
