# Generated by Django 4.2.2 on 2023-12-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics_team', '0002_alter_graphics_banner_image_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphics_link',
            name='graphics_form_link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
