# Generated by Django 4.2.2 on 2024-02-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics_team', '0003_alter_graphics_banner_image_selected_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graphics_Drive_links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_title', models.TextField(blank=True, default='', null=True)),
                ('link', models.URLField(blank=True, default='www.google_drive_link.com', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Graphics_Drive_link',
            },
        ),
    ]
