# Generated by Django 4.2.2 on 2024-02-08 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphics_team', '0004_graphics_drive_links'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graphics_drive_links',
            options={'ordering': ['-created_at'], 'verbose_name': 'Graphics_Drive_link'},
        ),
    ]
