# Generated by Django 4.1.2 on 2022-12-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('probable_date', models.DateField(blank=True, null=True)),
                ('collaboration_with', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Registered Events',
            },
        ),
    ]
