# Generated by Django 4.1.2 on 2022-12-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insb_central', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='description',
            new_name='event_description',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='name',
            new_name='event_name',
        ),
        migrations.AddField(
            model_name='events',
            name='final_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
