# Generated by Django 4.1.2 on 2022-12-01 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insb_central', '0002_rename_description_events_event_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission_criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Venue_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Media_Selected_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_image', models.ImageField(blank=True, default=None, null=True, upload_to='event_selected_pictures')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insb_central.events')),
            ],
        ),
        migrations.CreateModel(
            name='Media_Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_link', models.URLField(blank=True, max_length=300, null=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insb_central.events')),
            ],
        ),
        migrations.CreateModel(
            name='Event_Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insb_central.events')),
                ('venue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insb_central.venue_list')),
            ],
        ),
        migrations.CreateModel(
            name='Event_Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_proposal', models.FileField(blank=True, default=None, null=True, upload_to='event_proposals')),
                ('proposal_template', models.FileField(blank=True, default=None, null=True, upload_to='event_proposals')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insb_central.events')),
            ],
        ),
    ]
