# Generated by Django 4.1.2 on 2022-12-08 05:33

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insb_central', '0003_permission_criteria_venue_list_media_selected_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission_criteria',
            name='template',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='Permission Templates'), upload_to=''),
        ),
    ]
