# Generated by Django 4.1.2 on 2022-12-08 07:05

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insb_central', '0004_permission_criteria_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Proposal_Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('proposal_template', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='Template-Event Proposal'), upload_to='')),
            ],
            options={
                'verbose_name': 'Event Proposal Templates',
            },
        ),
        migrations.CreateModel(
            name='Logistic_Item_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_list', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Logistic Item List',
            },
        ),
        migrations.AlterModelOptions(
            name='permission_criteria',
            options={'verbose_name': 'Permission Categories'},
        ),
        migrations.RemoveField(
            model_name='event_proposal',
            name='proposal_template',
        ),
        migrations.AlterField(
            model_name='event_proposal',
            name='event_proposal',
            field=models.FileField(blank=True, default=None, null=True, storage=django.core.files.storage.FileSystemStorage(location='Event Proposals'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='media_selected_images',
            name='selected_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='Event Selected Images/'),
        ),
        migrations.CreateModel(
            name='Graphics_Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graphics_link', models.URLField(blank=True, max_length=300, null=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insb_central.events')),
            ],
        ),
        migrations.CreateModel(
            name='Graphics_Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graphics_file', models.FileField(blank=True, null=True, upload_to='Graphics Items/')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insb_central.events')),
            ],
        ),
        migrations.CreateModel(
            name='Event_Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_status', models.BooleanField(default=False)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insb_central.events')),
                ('permission_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insb_central.permission_criteria')),
            ],
        ),
        migrations.CreateModel(
            name='Event_Logistic_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buying_status', models.BooleanField(default=False)),
                ('item_reciept', models.FileField(blank=True, null=True, upload_to='Logistic Reciepts/')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insb_central.events')),
                ('logistic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insb_central.logistic_item_list')),
            ],
        ),
    ]
