# Generated by Django 4.0.5 on 2023-01-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insb_central', '0005_event_proposal_template_logistic_item_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('super_event_name', models.CharField(max_length=150)),
                ('super_event_description', models.CharField(blank=True, max_length=500, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mother Event',
            },
        ),
        migrations.AlterModelOptions(
            name='event_proposal',
            options={'verbose_name': 'Event Proposal'},
        ),
        migrations.AlterModelOptions(
            name='event_venue',
            options={'verbose_name': 'Event Venue'},
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Registered Event'},
        ),
        migrations.AlterModelOptions(
            name='venue_list',
            options={'verbose_name': 'Venue'},
        ),
    ]
