# Generated by Django 4.0.5 on 2023-01-20 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0004_alter_chapters_society_and_affinity_groups_options_and_more'),
        ('insb_central', '0006_superevents_alter_event_proposal_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='collaboration_with',
        ),
        migrations.AddField(
            model_name='event_venue',
            name='booking_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='events',
            name='event_organiser',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='port.chapters_society_and_affinity_groups'),
        ),
        migrations.AddField(
            model_name='events',
            name='registration_fee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='events',
            name='super_event_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insb_central.superevents'),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='IntraBranchCollaborations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaboration_with', models.CharField(blank=True, max_length=300, null=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insb_central.events')),
            ],
            options={
                'verbose_name': 'Intra Branch Collaborations',
            },
        ),
        migrations.CreateModel(
            name='InterBranchCollaborations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaboration_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='port.chapters_society_and_affinity_groups')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insb_central.events')),
            ],
            options={
                'verbose_name': 'Inter Branch Collaborations',
            },
        ),
    ]
