# Generated by Django 4.0.5 on 2023-01-20 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_and_operations_team', '0001_initial'),
        ('insb_central', '0007_remove_events_collaboration_with_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_logistic_items',
            name='logistic_id',
        ),
        migrations.AddField(
            model_name='event_logistic_items',
            name='logistic_item_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics_and_operations_team.logistic_item_list'),
        ),
        migrations.AddField(
            model_name='event_logistic_items',
            name='spending_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Logistic_Item_List',
        ),
    ]
