# Generated by Django 4.0.5 on 2023-01-20 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events_and_management_team', '0001_initial'),
        ('insb_central', '0008_remove_event_logistic_items_logistic_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event_Proposal_Template',
        ),
        migrations.AlterField(
            model_name='event_permission',
            name='permission_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_and_management_team.permission_criteria'),
        ),
        migrations.AlterField(
            model_name='event_venue',
            name='venue_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_and_management_team.venue_list'),
        ),
        migrations.DeleteModel(
            name='Permission_criteria',
        ),
        migrations.DeleteModel(
            name='Venue_List',
        ),
    ]
