# Generated by Django 3.2.16 on 2023-01-28 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insb_central', '0009_delete_event_proposal_template_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='superevents',
            options={'verbose_name': 'Super Event'},
        ),
    ]
