# Generated by Django 4.2.2 on 2023-10-08 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_team', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media_images',
            old_name='selected_image',
            new_name='selected_images',
        ),
    ]
