# Generated by Django 4.2.2 on 2024-01-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media_images',
            name='selected_images',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='Event Selected Images/'),
        ),
    ]
