# Generated by Django 4.2.2 on 2024-01-18 05:43

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('media_team', '0002_alter_media_images_selected_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media_images',
            name='selected_images',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='Event_Selected_Images/'),
        ),
    ]
