# Generated by Django 4.2.2 on 2023-12-05 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('central_events', '0003_events_rename_event_categories_event_category_and_more'),
        ('media_team', '0003_alter_media_images_selected_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media_images',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central_events.events'),
        ),
        migrations.AlterField(
            model_name='media_link',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central_events.events'),
        ),
    ]
