# Generated by Django 4.2.2 on 2024-01-10 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_administration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch_data_access',
            name='manage_web_home_access',
        ),
    ]
