# Generated by Django 4.2.2 on 2024-02-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cwp_data_access',
            name='content_access',
            field=models.BooleanField(default=False, verbose_name='Content Access'),
        ),
        migrations.AddField(
            model_name='cwp_data_access',
            name='content_view_access',
            field=models.BooleanField(default=False, verbose_name='Content View Access'),
        ),
        migrations.AddField(
            model_name='graphics_data_access',
            name='graphics_access',
            field=models.BooleanField(default=False, verbose_name='Graphics Access'),
        ),
        migrations.AddField(
            model_name='graphics_data_access',
            name='graphics_view_access',
            field=models.BooleanField(default=False, verbose_name='Graphics View Access'),
        ),
    ]
