# Generated by Django 4.2.2 on 2024-01-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_administration', '0002_remove_branch_data_access_manage_web_home_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch_data_access',
            name='panel_edit_access',
            field=models.BooleanField(default=False),
        ),
    ]
