# Generated by Django 4.0.5 on 2022-12-19 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0002_roles_and_position'),
        ('users', '0014_remove_data_access_criteria_and_more'),
        ('system_administration', '0002_alter_adminusers_options_remove_adminusers_userid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access_Criterias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria_name', models.CharField(default='All', max_length=30)),
            ],
            options={
                'verbose_name': 'Data Access Criteria',
            },
        ),
        migrations.CreateModel(
            name='Data_Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_administration.access_criterias')),
                ('ieee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.members')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='port.teams')),
            ],
            options={
                'verbose_name': 'Team Data Access',
            },
        ),
    ]
