# Generated by Django 4.0.5 on 2022-12-19 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_administration', '0003_access_criterias_data_access'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_access',
            old_name='criteria',
            new_name='restricted_criteria',
        ),
    ]
