# Generated by Django 4.2.2 on 2024-01-11 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_administration', '0003_branch_data_access_panel_edit_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch_data_access',
            name='panel_edit_access',
        ),
    ]
