# Generated by Django 4.0.5 on 2022-12-19 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_data_access_criteria_and_more'),
        ('port', '0002_roles_and_position'),
        ('system_administration', '0004_rename_criteria_data_access_restricted_criteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_access',
            name='ieee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.members', verbose_name='IEEE ID'),
        ),
        migrations.AlterField(
            model_name='data_access',
            name='restricted_criteria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system_administration.access_criterias', verbose_name='Accepted Permission Criteria'),
        ),
        migrations.AlterField(
            model_name='data_access',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='port.teams', verbose_name='Team'),
        ),
    ]
