# Generated by Django 4.2.2 on 2024-02-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_administration', '0004_system_restrict_sc_ag_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch_data_access',
            name='manage_award_access',
            field=models.BooleanField(default=False),
        ),
    ]
