# Generated by Django 4.2.2 on 2024-01-12 20:56

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('system_administration', '0004_remove_branch_data_access_panel_edit_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminusers',
            name='profile_picture',
            field=django_resized.forms.ResizedImageField(crop=None, default='Admin/admin_profile_pictures/default_profile_picture.png', force_format=None, keep_meta=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='Admin/admin_profile_pictures/'),
        ),
    ]
