# Generated by Django 4.2.2 on 2024-01-13 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_administration', '0005_alter_adminusers_profile_picture'),
        ('system_administration', '0005_sc_ag_data_access_manage_web_access_and_more'),
    ]

    operations = [
    ]
