# Generated by Django 4.2.2 on 2024-03-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_administration', '0005_branch_data_access_manage_award_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='count_down',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
