# Generated by Django 4.2.2 on 2024-03-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_administration', '0005_branch_data_access_manage_award_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch_data_access',
            name='create_individual_task_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branch_data_access',
            name='create_team_task_access',
            field=models.BooleanField(default=False),
        ),
    ]
