# Generated by Django 4.0.5 on 2022-12-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_administration', '0006_team_data_access_delete_data_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access_criterias',
            name='criteria_name',
            field=models.CharField(default='all', max_length=30),
        ),
    ]
