# Generated by Django 4.2.2 on 2024-03-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_administration', '0006_system_count_down'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='count_down_bool',
            field=models.BooleanField(default=False),
        ),
    ]
