# Generated by Django 4.2.2 on 2024-03-22 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_administration', '0007_system_count_down_bool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='count_down_bool',
        ),
    ]
