# Generated by Django 4.0.5 on 2022-12-20 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0002_roles_and_position'),
        ('system_administration', '0007_alter_access_criterias_criteria_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='access_criterias',
            name='team',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='port.teams'),
        ),
    ]
