# Generated by Django 4.2.2 on 2024-03-29 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_administration', '0006_branch_data_access_create_individual_task_access_and_more'),
        ('system_administration', '0008_remove_system_count_down_bool'),
    ]

    operations = [
    ]
