# Generated by Django 4.0.5 on 2022-12-31 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_members_position'),
        ('system_administration', '0008_access_criterias_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='MDT_Data_Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria_name', models.CharField(default='All', max_length=50)),
                ('has_permission', models.BooleanField(default=False, verbose_name='Permission Status')),
                ('ieee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.members', verbose_name='IEEE ID')),
            ],
            options={
                'verbose_name': 'Team Data Access',
            },
        ),
        migrations.RemoveField(
            model_name='team_data_access',
            name='criteria',
        ),
        migrations.RemoveField(
            model_name='team_data_access',
            name='ieee_id',
        ),
        migrations.RemoveField(
            model_name='team_data_access',
            name='team',
        ),
        migrations.DeleteModel(
            name='Access_Criterias',
        ),
        migrations.DeleteModel(
            name='Team_Data_Access',
        ),
    ]
