# Generated by Django 4.2.2 on 2024-05-31 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_administration', '0009_merge_20240330_0052'),
        ('system_administration', '0009_merge_20240407_1652'),
    ]

    operations = [
    ]
