# Generated by Django 4.2.2 on 2024-06-23 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('system_administration', '0010_merge_20240531_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='General_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('log_details', models.JSONField()),
                ('update_number', models.IntegerField(blank=True, default=0, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'General Log',
            },
        ),
    ]
