# Generated by Django 4.0.5 on 2023-01-06 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_administration', '0011_adminusers_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminusers',
            name='profile_picture',
        ),
    ]
