# Generated by Django 4.0.5 on 2023-01-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_administration', '0012_remove_adminusers_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminusers',
            name='profile_picture',
            field=models.ImageField(default='Admin/admin_profile_pictures/default_profile_picture.png', upload_to='Admin/admin_profile_pictures/'),
        ),
    ]
