# Generated by Django 4.2.2 on 2024-09-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_administration', '0012_branch_data_access_manage_custom_notification_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch_data_access',
            name='manage_email_access',
            field=models.BooleanField(default=False),
        ),
    ]
