# Generated by Django 4.0.5 on 2023-01-09 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_members_last_renewal'),
        ('system_administration', '0013_adminusers_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='MDT_Data_Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewal_access', models.BooleanField(default=False, verbose_name='Membership Renewal Data Access Permission')),
                ('insb_member_details', models.BooleanField(default=False, verbose_name='INSB Registered Member Details Peemission')),
                ('recruitment_session', models.BooleanField(default=False, verbose_name='Recruitment Data View Permission')),
                ('recruited_member_details', models.BooleanField(default=False, verbose_name='Rectuited Member Details Peemission')),
                ('ieee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.members', verbose_name='IEEE ID')),
            ],
            options={
                'verbose_name': 'Membership Development Team Data Access',
            },
        ),
        migrations.RemoveField(
            model_name='team_data_access',
            name='criteria',
        ),
        migrations.RemoveField(
            model_name='team_data_access',
            name='ieee_id',
        ),
        migrations.RemoveField(
            model_name='team_data_access',
            name='team',
        ),
        migrations.DeleteModel(
            name='Access_Criterias',
        ),
        migrations.DeleteModel(
            name='Team_Data_Access',
        ),
    ]
