# Generated by Django 4.0.5 on 2023-01-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_administration', '0014_mdt_data_access_remove_team_data_access_criteria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mdt_data_access',
            old_name='renewal_access',
            new_name='renewal_data_access',
        ),
        migrations.AlterField(
            model_name='mdt_data_access',
            name='insb_member_details',
            field=models.BooleanField(default=False, verbose_name='INSB Registered Member Details Permission'),
        ),
        migrations.AlterField(
            model_name='mdt_data_access',
            name='recruited_member_details',
            field=models.BooleanField(default=False, verbose_name='Rectuited Member Details Permission'),
        ),
    ]
