# Generated by Django 3.2.16 on 2023-02-24 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_administration', '0015_rename_renewal_access_mdt_data_access_renewal_data_access_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer_criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Developer Criteria',
            },
        ),
        migrations.CreateModel(
            name='Project_leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('developer_decription', models.CharField(blank=True, max_length=200, null=True)),
                ('developers_picture', models.ImageField(blank=True, default='user_profile_pictures/default_profile_picture.png', null=True, upload_to='Admin/developers_pictures')),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('developer_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system_administration.developer_criteria')),
            ],
            options={
                'verbose_name': 'Project Lead',
            },
        ),
        migrations.CreateModel(
            name='Project_Developers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('developer_decription', models.CharField(blank=True, max_length=200, null=True)),
                ('developers_picture', models.ImageField(blank=True, default='user_profile_pictures/default_profile_picture.png', null=True, upload_to='Admin/developers_pictures')),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('developer_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system_administration.developer_criteria')),
            ],
            options={
                'verbose_name': 'Project Developers',
            },
        ),
    ]
