# Generated by Django 3.2.16 on 2023-02-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_administration', '0016_developer_criteria_project_developers_project_leads'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_developers',
            name='reputation_point',
            field=models.IntegerField(default=0),
        ),
    ]
