# Generated by Django 4.2.2 on 2023-07-23 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_resetpasswordtokentable'),
        ('system_administration', '0017_project_developers_reputation_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMT_Data_Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_task_data_access', models.BooleanField(default=False, verbose_name='Task Assign Data Access Permission')),
                ('manage_team_data_access', models.BooleanField(default=False, verbose_name='Manage Team Permission')),
                ('ieee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.members', verbose_name='IEEE ID')),
            ],
            options={
                'verbose_name': 'Events and Management Team Data Access',
            },
        ),
    ]
