# Generated by Django 4.2.2 on 2023-08-24 16:09

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('system_administration', '0025_fct_data_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminusers',
            name='profile_picture',
            field=django_resized.forms.ResizedImageField(crop=None, default='Admin/admin_profile_pictures/default_profile_picture.png', force_format='JPEG', keep_meta=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='Admin/admin_profile_pictures/'),
        ),
    ]
