# Generated by Django 4.2.2 on 2023-10-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_administration', '0026_alter_adminusers_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='system',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_under_maintenance', models.BooleanField(default=False)),
                ('main_website_under_maintenance', models.BooleanField(default=False)),
                ('portal_under_maintenance', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'System Handling',
            },
        ),
    ]
