# Generated by Django 4.2.2 on 2023-11-19 19:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_administration', '0029_alter_branch_data_access_ieee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemErrors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('error_name', models.CharField(max_length=100)),
                ('error_traceback', ckeditor.fields.RichTextField(max_length=1000)),
                ('error_fix_status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'System Errors',
            },
        ),
    ]
