# Generated by Django 4.2.2 on 2023-11-19 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_administration', '0030_systemerrors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemerrors',
            options={'verbose_name': 'System Error'},
        ),
    ]
