# Generated by Django 4.2.2 on 2023-11-28 18:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_administration', '0031_alter_systemerrors_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemerrors',
            name='error_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='systemerrors',
            name='error_traceback',
            field=ckeditor.fields.RichTextField(max_length=3000),
        ),
    ]
