# Generated by Django 4.2.2 on 2023-12-08 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_alumni_members_alter_panel_members_ex_member_and_more'),
        ('system_administration', '0032_alter_systemerrors_error_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SC_AG_Data_Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_details_access', models.BooleanField(default=False)),
                ('create_event_access', models.BooleanField(default=False)),
                ('event_details_edit_access', models.BooleanField(default=False)),
                ('panel_edit_access', models.BooleanField(default=False)),
                ('membership_renewal_access', models.BooleanField(default=False)),
                ('manage_access', models.BooleanField(default=False)),
                ('ieee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.members')),
            ],
            options={
                'verbose_name': 'Chapter, Society, Affinity Group Data Access',
            },
        ),
    ]
