# Generated by Django 4.2.2 on 2023-12-09 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0027_rename_color_code_chapters_society_and_affinity_groups_primary_color_code'),
        ('system_administration', '0033_sc_ag_data_access'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sc_ag_data_access',
            options={'verbose_name': 'Manage Data Access - Chapter, Society, Affinity Group'},
        ),
        migrations.AddField(
            model_name='sc_ag_data_access',
            name='data_access_of',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='port.chapters_society_and_affinity_groups'),
        ),
    ]
