# Generated by Django 4.2.2 on 2023-12-09 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_administration', '0034_alter_sc_ag_data_access_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sc_ag_data_access',
            old_name='ieee_id',
            new_name='member',
        ),
    ]
