# Generated by Django 4.2.2 on 2023-12-09 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chapters_and_affinity_group', '0004_delete_gg'),
        ('system_administration', '0035_rename_ieee_id_sc_ag_data_access_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sc_ag_data_access',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chapters_and_affinity_group.sc_ag_members'),
        ),
    ]
