# Generated by Django 4.2.2 on 2023-12-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_administration', '0036_alter_sc_ag_data_access_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphics_data_access',
            name='event_access',
            field=models.BooleanField(default=False),
        ),
    ]
