# Generated by Django 4.2.2 on 2023-12-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_administration', '0037_graphics_data_access_event_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphics_data_access',
            name='event_access',
            field=models.BooleanField(default=False, verbose_name='Event Access'),
        ),
        migrations.AlterField(
            model_name='graphics_data_access',
            name='manage_team_access',
            field=models.BooleanField(default=False, verbose_name='Manage Team Access'),
        ),
    ]
