# Generated by Django 4.2.2 on 2023-12-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_administration', '0038_alter_graphics_data_access_event_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media_data_access',
            name='event_access',
            field=models.BooleanField(default=False, verbose_name='Event Access'),
        ),
    ]
