# Generated by Django 4.2.2 on 2023-12-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_administration', '0039_media_data_access_event_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='cwp_data_access',
            name='event_access',
            field=models.BooleanField(default=False, verbose_name='Event Access'),
        ),
    ]
