# Generated by Django 4.2.2 on 2023-12-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_administration', '0040_cwp_data_access_event_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='email_access',
            field=models.BooleanField(default=False),
        ),
    ]
