# Generated by Django 4.2.2 on 2023-12-20 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_administration', '0041_system_email_access'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system',
            old_name='email_access',
            new_name='scheduling_under_maintenance',
        ),
    ]
