# Generated by Django 4.2.2 on 2023-08-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manage_Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manage_team_access', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Manage Team Access',
            },
        ),
    ]
