# Generated by Django 4.2.2 on 2024-01-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_relation_team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manage_team',
            name='manage_email_access',
            field=models.BooleanField(default=False, verbose_name='Email Access'),
        ),
        migrations.AlterField(
            model_name='manage_team',
            name='manage_team_access',
            field=models.BooleanField(default=False, verbose_name='Team Access'),
        ),
    ]
