# Generated by Django 4.2.2 on 2023-12-18 18:57

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_relation_team', '0002_manage_team_ieee_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_Attachements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('email_content', models.FileField(blank=True, default=None, null=True, storage=django.core.files.storage.FileSystemStorage(location='Email Attachments'), upload_to='')),
            ],
            options={
                'verbose_name': 'Email Attachments',
            },
        ),
    ]
