# Generated by Django 4.2.2 on 2024-08-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_relation_team', '0002_alter_email_attachements_email_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_unique_id', models.CharField(max_length=20)),
                ('subject', models.TextField(blank=True, null=True)),
                ('drafts', models.JSONField(blank=True, default=dict, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Email Draft',
            },
        ),
        migrations.DeleteModel(
            name='Email_Attachements',
        ),
    ]
