# Generated by Django 4.2.2 on 2024-09-09 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_relation_team', '0003_email_draft_delete_email_attachements'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email_Draft',
        ),
    ]
