# Generated by Django 4.2.2 on 2024-01-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logistic_Item_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_list', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Logistic Item List',
            },
        ),
    ]
