# Generated by Django 4.2.2 on 2023-10-19 17:39

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('port', '0018_roles_and_position_is_sc_ag_eb_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerPictureWithStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/homepage/ribbon_picture')),
            ],
            options={
                'verbose_name': 'Banner Picture with Statistics in Homepage',
            },
        ),
        migrations.CreateModel(
            name='Blog_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_category', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='HomepageBannerPictureWithText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_picture', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/homepage/banner_pictures')),
                ('first_layer_text', models.CharField(default='FOCUSING LIMELIGHT ON', max_length=50)),
                ('second_layer_text', models.CharField(default='THE', max_length=20)),
                ('second_layer_text_colored', models.CharField(default='MASTERMINDS', max_length=20)),
                ('third_layer_text', models.TextField(max_length=500)),
                ('button_text', models.CharField(default='About INSB', max_length=50)),
                ('button_url', models.CharField(default='#', max_length=200)),
            ],
            options={
                'verbose_name': 'Homepage Banner Picture With Texts',
            },
        ),
        migrations.CreateModel(
            name='Research_Papers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('research_banner_picture', models.ImageField(default='main_website/Research_pictures/default_research_banner_picture.png', upload_to='main_website/Research_pictures/')),
                ('author_names', models.CharField(max_length=1000)),
                ('publication_link', models.URLField()),
            ],
            options={
                'verbose_name': 'Research Paper',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('blog_banner_picture', models.ImageField(default='main_website/Blog_banner_pictures/default_blog_banner_picture.png', upload_to='main_website/Blog_pictures/')),
                ('publisher', models.CharField(max_length=160)),
                ('description', models.TextField(default='None', max_length=5000)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_website.blog_category')),
                ('chapter_society_affinity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='port.chapters_society_and_affinity_groups')),
            ],
            options={
                'verbose_name': 'Blog',
            },
        ),
    ]
