# Generated by Django 4.2.2 on 2023-07-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Research_Papers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('research_banner_picture', models.ImageField(blank=True, default='main_website/Research_pictures/default_research_banner_picture.png', null=True, upload_to='main_website/Research_pictures/')),
                ('author_names', models.CharField(max_length=1000)),
                ('publication_link', models.URLField()),
            ],
            options={
                'verbose_name': 'Research Paper',
            },
        ),
    ]
