# Generated by Django 4.2.2 on 2024-01-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_ieee',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='main_website_files/About/IEEE/About Image/'),
        ),
        migrations.AlterField(
            model_name='about_ieee',
            name='community_image',
            field=models.ImageField(blank=True, null=True, upload_to='main_website_files/About/IEEE/Community Image/'),
        ),
        migrations.AlterField(
            model_name='about_ieee',
            name='innovations_and_developments_image',
            field=models.ImageField(blank=True, null=True, upload_to='main_website_files/About/IEEE/Innovation Development Image/'),
        ),
        migrations.AlterField(
            model_name='about_ieee',
            name='quality_image',
            field=models.ImageField(blank=True, null=True, upload_to='main_website_files/About/IEEE/Quality Image/'),
        ),
        migrations.AlterField(
            model_name='about_ieee',
            name='students_and_member_activities_image',
            field=models.ImageField(blank=True, null=True, upload_to='main_website_files/About/IEEE/Student Member Activity Image/'),
        ),
        migrations.AlterField(
            model_name='ieee_bangladesh_section',
            name='ieee_bangladesh_logo',
            field=models.ImageField(blank=True, null=True, upload_to='main_website_files/About/IEEE Bangladesh Section/logo/'),
        ),
        migrations.AlterField(
            model_name='ieee_bangladesh_section',
            name='member_and_volunteer_picture',
            field=models.ImageField(blank=True, null=True, upload_to='main_website_files/About/IEEE Bangladesh Section/member_volunteer_picture/'),
        ),
        migrations.AlterField(
            model_name='ieee_bangladesh_section_gallery',
            name='picture',
            field=models.ImageField(upload_to='main_website_files/About/IEEE Bangladesh Section/Gallery/'),
        ),
        migrations.AlterField(
            model_name='ieee_nsu_student_branch',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='main_website_files/About/IEEE NSU Student Branch/About Image/'),
        ),
        migrations.AlterField(
            model_name='ieee_nsu_student_branch',
            name='ias_image',
            field=models.ImageField(blank=True, null=True, upload_to='main_website_files/About/IEEE NSU Student Branch/IAS Image/'),
        ),
        migrations.AlterField(
            model_name='ieee_nsu_student_branch',
            name='mission_image',
            field=models.ImageField(blank=True, null=True, upload_to='main_website_files/About/IEEE NSU Student Branch/Mission Image/'),
        ),
        migrations.AlterField(
            model_name='ieee_nsu_student_branch',
            name='pes_image',
            field=models.ImageField(blank=True, null=True, upload_to='main_website_files/About/IEEE NSU Student Branch/PES Image/'),
        ),
        migrations.AlterField(
            model_name='ieee_nsu_student_branch',
            name='ras_image',
            field=models.ImageField(blank=True, null=True, upload_to='main_website_files/About/IEEE NSU Student Branch/RAS Image/'),
        ),
        migrations.AlterField(
            model_name='ieee_nsu_student_branch',
            name='vision_image',
            field=models.ImageField(blank=True, null=True, upload_to='main_website_files/About/IEEE NSU Student Branch/Vision Image/'),
        ),
        migrations.AlterField(
            model_name='ieee_nsu_student_branch',
            name='wie_image',
            field=models.ImageField(blank=True, null=True, upload_to='main_website_files/About/IEEE NSU Student Branch/WIE Image/'),
        ),
        migrations.AlterField(
            model_name='ieee_region_10',
            name='background_picture_parallax',
            field=models.ImageField(blank=True, null=True, upload_to='main_website_files/About/IEEE Region 10/Parallax Background Image/'),
        ),
        migrations.AlterField(
            model_name='ieee_region_10',
            name='events_and_conference_image',
            field=models.ImageField(blank=True, null=True, upload_to='main_website_files/About/IEEE Region 10/Events and Conference Image/'),
        ),
        migrations.AlterField(
            model_name='ieee_region_10',
            name='ieee_region_10_image',
            field=models.ImageField(blank=True, null=True, upload_to='main_website_files/About/IEEE Region 10/Region 10 Image/'),
        ),
        migrations.AlterField(
            model_name='ieee_region_10',
            name='membership_development_image',
            field=models.ImageField(blank=True, null=True, upload_to='main_website_files/About/IEEE Region 10/Membership Development Image/'),
        ),
        migrations.AlterField(
            model_name='ieee_region_10',
            name='young_professionals_image',
            field=models.ImageField(blank=True, null=True, upload_to='main_website_files/About/IEEE Region 10/Young Professionals Image/'),
        ),
    ]
