# Generated by Django 4.2.2 on 2024-01-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0002_galleryimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_link', models.URLField()),
                ('upload_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Gallery Video',
            },
        ),
        migrations.AddField(
            model_name='galleryimages',
            name='upload_date',
            field=models.DateField(default='2023-2-01'),
            preserve_default=False,
        ),
    ]
