# Generated by Django 4.2.2 on 2024-01-18 05:43

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0002_alter_about_ieee_about_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_ieee',
            name='about_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE/About_Image/'),
        ),
        migrations.AlterField(
            model_name='about_ieee',
            name='community_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE/Community_Image/'),
        ),
        migrations.AlterField(
            model_name='about_ieee',
            name='innovations_and_developments_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE/Innovation_Development_Image/'),
        ),
        migrations.AlterField(
            model_name='about_ieee',
            name='quality_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE/Quality_Image/'),
        ),
        migrations.AlterField(
            model_name='about_ieee',
            name='students_and_member_activities_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE/Student_Member_Activity_Image/'),
        ),
        migrations.AlterField(
            model_name='ieee_bangladesh_section',
            name='ieee_bangladesh_logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE_Bangladesh_Section/logo/'),
        ),
        migrations.AlterField(
            model_name='ieee_bangladesh_section',
            name='member_and_volunteer_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE_Bangladesh_Section/member_volunteer_picture/'),
        ),
        migrations.AlterField(
            model_name='ieee_bangladesh_section_gallery',
            name='picture',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE_Bangladesh_Section/Gallery/'),
        ),
        migrations.AlterField(
            model_name='ieee_nsu_student_branch',
            name='about_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE_NSU_Student_Branch/About_Image/'),
        ),
        migrations.AlterField(
            model_name='ieee_nsu_student_branch',
            name='ias_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE_NSU_Student_Branch/IAS_Image/'),
        ),
        migrations.AlterField(
            model_name='ieee_nsu_student_branch',
            name='mission_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE_NSU_Student_Branch/Mission_Image/'),
        ),
        migrations.AlterField(
            model_name='ieee_nsu_student_branch',
            name='pes_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE_NSU_Student_Branch/PES_Image/'),
        ),
        migrations.AlterField(
            model_name='ieee_nsu_student_branch',
            name='ras_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE_NSU_Student_Branch/RAS_Image/'),
        ),
        migrations.AlterField(
            model_name='ieee_nsu_student_branch',
            name='vision_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE_NSU Student_Branch/Vision_Image/'),
        ),
        migrations.AlterField(
            model_name='ieee_nsu_student_branch',
            name='wie_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE_NSU_Student_Branch/WIE_Image/'),
        ),
        migrations.AlterField(
            model_name='ieee_region_10',
            name='background_picture_parallax',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE_Region_10/Parallax_Background_Image/'),
        ),
        migrations.AlterField(
            model_name='ieee_region_10',
            name='events_and_conference_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE_Region_10/Events_and_Conference_Image/'),
        ),
        migrations.AlterField(
            model_name='ieee_region_10',
            name='ieee_region_10_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE_Region_10/Region_10_Image/'),
        ),
        migrations.AlterField(
            model_name='ieee_region_10',
            name='membership_development_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE_Region_10/Membership_Development_Image/'),
        ),
        migrations.AlterField(
            model_name='ieee_region_10',
            name='young_professionals_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE_Region_10/Young_Professionals_Image/'),
        ),
    ]
