# Generated by Django 4.2.2 on 2024-01-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0002_ieee_bangladesh_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage_Thoughts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'HomePage Thoughts',
            },
        ),
    ]
