# Generated by Django 4.2.2 on 2024-01-03 11:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0002_ieee_bangladesh_section_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ieee_bangladesh_section',
            options={'verbose_name': 'IEEE Bangladesh Section'},
        ),
        migrations.AddField(
            model_name='ieee_bangladesh_section',
            name='community_and_society_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
