# Generated by Django 4.2.2 on 2023-10-30 06:41

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0002_bannerpicturewithstat'),
    ]

    # operations = [
    #     migrations.CreateModel(
    #         name='HomePageTopBanner',
    #         fields=[
    #             ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    #             ('banner_picture', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/homepage/banner_pictures')),
    #             ('first_layer_text', models.CharField(default='FOCUSING LIMELIGHT ON', max_length=50)),
    #             ('second_layer_text', models.CharField(default='THE', max_length=20)),
    #             ('second_layer_text_colored', models.CharField(default='MASTERMINDS', max_length=20)),
    #             ('third_layer_text', models.TextField(max_length=500)),
    #             ('button_text', models.CharField(default='About INSB', max_length=50)),
    #             ('button_url', models.CharField(default='#', max_length=200)),
    #         ],
    #         options={
    #             'verbose_name': 'Homepage Banner Picture With Texts',
    #         },
    #     ),
    # ]
