# Generated by Django 4.2.2 on 2023-07-14 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0004_alter_chapters_society_and_affinity_groups_options_and_more'),
        ('main_website', '0002_blog_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('blog_banner_picture', models.ImageField(blank=True, default='main_website/Blog_banner_pictures/default_blog_banner_picture.png', null=True, upload_to='main_website/Blog_pictures/')),
                ('publisher', models.CharField(max_length=160)),
                ('description', models.TextField(default='None', max_length=5000)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_website.blog_category')),
                ('chapter_society_affinity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='port.chapters_society_and_affinity_groups')),
            ],
            options={
                'verbose_name': 'Blog',
            },
        ),
    ]
