# Generated by Django 4.2.2 on 2024-01-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0002_galleryvideos'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='ieee_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
