# Generated by Django 4.2.2 on 2023-07-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0003_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_banner_picture',
            field=models.ImageField(default='main_website/Blog_banner_pictures/default_blog_banner_picture.png', upload_to='main_website/Blog_pictures/'),
        ),
        migrations.AlterField(
            model_name='research_papers',
            name='research_banner_picture',
            field=models.ImageField(default='main_website/Research_pictures/default_research_banner_picture.png', upload_to='main_website/Research_pictures/'),
        ),
    ]
