# Generated by Django 4.2.2 on 2024-01-03 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0003_alter_ieee_bangladesh_section_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ieee_bangladesh_section_gallery',
            options={'verbose_name': 'IEEE Bangladesh Section Gallery'},
        ),
    ]
