# Generated by Django 4.2.2 on 2023-12-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0003_homepagetopbanner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagetopbanner',
            old_name='second_layer_text_colored',
            new_name='first_layer_text_colored',
        ),
        migrations.RemoveField(
            model_name='homepagetopbanner',
            name='second_layer_text',
        ),
        migrations.AlterField(
            model_name='homepagetopbanner',
            name='third_layer_text',
            field=models.TextField(max_length=200),
        ),
    ]
