# Generated by Django 4.2.2 on 2024-01-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0003_homepage_thoughts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ieee_bangladesh_section',
            name='about_ieee_bangladesh',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ieee_bangladesh_section',
            name='affinity_groups_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ieee_bangladesh_section',
            name='benefits_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ieee_bangladesh_section',
            name='community_and_society_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ieee_bangladesh_section',
            name='member_and_volunteer_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ieee_bangladesh_section',
            name='student_branches_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
