# Generated by Django 4.2.2 on 2024-01-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0003_galleryvideos_galleryimages_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryvideos',
            name='video_title',
            field=models.CharField(default='INSB Videos', max_length=100),
            preserve_default=False,
        ),
    ]
