# Generated by Django 4.2.2 on 2024-01-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0003_blog_ieee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_requested',
            field=models.CharField(blank=True, null=True),
        ),
    ]
