# Generated by Django 4.2.2 on 2024-01-18 06:39

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0003_alter_about_ieee_about_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ieee_nsu_student_branch',
            name='vision_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE_NSU_Student_Branch/Vision_Image/'),
        ),
    ]
