# Generated by Django 4.2.2 on 2024-01-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0004_alter_ieee_bangladesh_section_about_ieee_bangladesh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage_thoughts',
            name='author',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='homepage_thoughts',
            name='quote',
            field=models.TextField(),
        ),
    ]
