# Generated by Django 4.2.2 on 2024-01-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0004_galleryvideos_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='short_description',
            field=models.CharField(default='IEEE NSU SB Blogs', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='galleryvideos',
            name='video_link',
            field=models.URLField(help_text='Please use embed link if you are pasting a link of Youtube video!'),
        ),
    ]
