# Generated by Django 4.2.2 on 2024-01-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0004_blog_is_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='is_requested',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
