# Generated by Django 4.2.2 on 2024-01-03 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0004_alter_ieee_bangladesh_section_gallery_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ieee_bangladesh_section',
            name='community_and_society_description',
        ),
    ]
