# Generated by Django 4.2.2 on 2023-12-14 19:40

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0029_rename_is_volunteer_roles_and_position_is_core_volunteer'),
        ('main_website', '0004_rename_second_layer_text_colored_homepagetopbanner_first_layer_text_colored_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_name', models.CharField(max_length=100)),
                ('award_short_description', models.CharField(max_length=100)),
                ('award_long_description', ckeditor.fields.RichTextField(max_length=200)),
                ('award_picture', models.ImageField(blank=True, null=True, upload_to='main_website_files/achievements/')),
                ('award_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='port.chapters_society_and_affinity_groups')),
            ],
            options={
                'verbose_name': 'Achievements',
            },
        ),
    ]
