# Generated by Django 4.2.2 on 2023-08-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0004_alter_blog_blog_banner_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageBannerPictureWithText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_picture', models.ImageField(upload_to='main_website_files/homepage/banner_pictures')),
                ('first_layer_text', models.CharField(default='FOCUSING LIMELIGHT ON', max_length=50)),
                ('second_layer_text', models.CharField(default='THE', max_length=20)),
                ('second_layer_text_colored', models.CharField(default='MASTERMINDS', max_length=20)),
                ('third_layer_text', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Homepage Banner Picture With Texts',
            },
        ),
    ]
