# Generated by Django 4.2.2 on 2024-01-03 11:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0005_remove_ieee_bangladesh_section_community_and_society_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ieee_bangladesh_section',
            name='community_and_society_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
