# Generated by Django 4.2.2 on 2024-01-05 16:52

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0005_alter_homepage_thoughts_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_IEEE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_ieee', models.TextField(blank=True, null=True)),
                ('about_image', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE/')),
                ('community_description', models.TextField(blank=True, null=True)),
                ('community_image', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE/')),
                ('start_with_ieee_description', models.TextField(blank=True, null=True)),
                ('collaboration_description', models.TextField(blank=True, null=True)),
                ('publications_description', models.TextField(blank=True, null=True)),
                ('events_and_conferences_description', models.TextField(blank=True, null=True)),
                ('achievements_description', models.TextField(blank=True, null=True)),
                ('innovations_and_developments_description', models.TextField(blank=True, null=True)),
                ('innovations_and_developments_image', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE/')),
                ('students_and_member_activities_description', models.TextField(blank=True, null=True)),
                ('students_and_member_activities_image', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE/')),
                ('quality_description', models.TextField(blank=True, null=True)),
                ('quality_image', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE/')),
            ],
            options={
                'verbose_name': 'About IEEE',
            },
        ),
    ]
