# Generated by Django 4.2.2 on 2023-08-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0005_homepagebannerpicturewithtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagebannerpicturewithtext',
            name='third_layer_text',
            field=models.TextField(max_length=500),
        ),
    ]
