# Generated by Django 4.2.2 on 2024-01-05 19:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0005_blog_short_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='short_description',
            field=ckeditor.fields.RichTextField(max_length=200),
        ),
    ]
