# Generated by Django 4.2.2 on 2024-01-31 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0005_achievements_award_winning_datefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagetopbanner',
            name='third_layer_text',
            field=models.TextField(max_length=300),
        ),
    ]
