# Generated by Django 4.2.2 on 2023-08-15 06:56

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0006_alter_homepagebannerpicturewithtext_third_layer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagebannerpicturewithtext',
            name='banner_picture',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[1600, 820], upload_to='main_website_files/homepage/banner_pictures'),
        ),
    ]
