# Generated by Django 4.2.2 on 2023-12-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0006_remove_achievements_award_long_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='award_winning_year',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
