# Generated by Django 4.2.2 on 2024-01-08 06:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0006_alter_blog_is_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='research_papers',
            name='is_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='research_papers',
            name='short_description',
            field=ckeditor.fields.RichTextField(max_length=1000, verbose_name='Abstract'),
        ),
    ]
