# Generated by Django 4.2.2 on 2024-02-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0006_alter_homepagetopbanner_third_layer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolkit',
            name='ai_files',
            field=models.FileField(blank=True, null=True, upload_to='main_website_files/toolkit_ai_files/'),
        ),
    ]
