# Generated by Django 4.2.2 on 2024-01-05 19:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0006_alter_blog_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='Write with in 500 words!', max_length=5000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_description',
            field=ckeditor.fields.RichTextField(help_text='Write with in 50 words!', max_length=200),
        ),
    ]
