# Generated by Django 4.2.2 on 2024-01-06 06:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0007_alter_blog_description_alter_blog_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExemplaryMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=100)),
                ('former_position', models.CharField(blank=True, max_length=100, null=True)),
                ('activity_year', models.CharField(blank=True, max_length=50, null=True)),
                ('current_activity', models.CharField(blank=True, max_length=200, null=True)),
                ('facebook_account_link', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Exemplary Members',
            },
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='Write within 500 words!', max_length=5000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_description',
            field=ckeditor.fields.RichTextField(help_text='Write within 50 words!', max_length=200),
        ),
    ]
