# Generated by Django 4.2.2 on 2023-12-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0007_achievements_award_winning_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='award_picture',
            field=models.ImageField(default='default.png', upload_to='main_website_files/achievements/'),
            preserve_default=False,
        ),
    ]
