# Generated by Django 4.2.2 on 2024-01-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0007_page_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_ieee',
            name='asia_pacific_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about_ieee',
            name='customer_service_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='about_ieee',
            name='founders_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='about_ieee',
            name='ieee_computer_organization_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about_ieee',
            name='join_now_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about_ieee',
            name='learn_more_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about_ieee',
            name='mission_and_vision_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about_ieee',
            name='presidents_names',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
