# Generated by Django 4.2.2 on 2024-01-08 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0008_about_ieee_asia_pacific_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about_ieee',
            old_name='founders_name',
            new_name='founders_names',
        ),
    ]
