# Generated by Django 4.2.2 on 2024-01-06 04:50

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0008_alter_about_ieee_about_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/gallery_pictures/')),
                ('upload_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Gallery Image',
            },
        ),
        migrations.CreateModel(
            name='GalleryVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_link', models.URLField()),
                ('upload_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Gallery Video',
            },
        ),
    ]
