# Generated by Django 4.2.2 on 2024-05-13 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0008_alter_toolkit_ai_files'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VolunteerOfTheMonth',
        ),
    ]
