# Generated by Django 4.2.2 on 2023-12-15 09:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0008_alter_achievements_award_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='award_description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True),
        ),
    ]
