# Generated by Django 4.2.2 on 2024-01-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0009_rename_founders_name_about_ieee_founders_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='ieee_bangladesh_section',
            name='achievements_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ieee_bangladesh_section',
            name='chair_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ieee_bangladesh_section',
            name='chair_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ieee_bangladesh_section',
            name='ieee_bd_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ieee_bangladesh_section',
            name='office_secretary_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ieee_bangladesh_section',
            name='office_secretary_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ieee_bangladesh_section',
            name='secretary_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ieee_bangladesh_section',
            name='secretary_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
