# Generated by Django 4.2.2 on 2024-01-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0009_exemplarymembers_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='exemplarymembers',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
