# Generated by Django 4.2.2 on 2024-01-08 15:23

import ckeditor.fields
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0009_alter_research_papers_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toolkit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('picture', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/toolkit_pictures/')),
                ('color_codes', ckeditor.fields.RichTextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Toolkit',
            },
        ),
    ]
