# Generated by Django 4.2.2 on 2023-12-15 19:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0009_alter_achievements_award_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=150)),
                ('news_subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('news_description', ckeditor.fields.RichTextField(max_length=500)),
                ('news_picture', models.ImageField(upload_to='main_website_files/news/')),
            ],
            options={
                'verbose_name': 'News',
            },
        ),
    ]
