# Generated by Django 4.2.2 on 2023-08-15 07:06

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0010_alter_homepagebannerpicturewithtext_banner_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagebannerpicturewithtext',
            name='banner_picture',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=80, scale=0.5, size=[1920, 1080], upload_to='main_website_files/homepage/banner_pictures'),
        ),
    ]
