# Generated by Django 4.2.2 on 2024-01-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0010_exemplarymembers_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='exemplarymembers',
            name='member_picture',
            field=models.ImageField(blank=True, null=True, upload_to='main_website_files/exemplary_members_picture/'),
        ),
        migrations.AlterField(
            model_name='exemplarymembers',
            name='rank',
            field=models.IntegerField(blank=True, help_text='This is used to sort exemplary members in the main website', null=True),
        ),
    ]
