# Generated by Django 4.2.2 on 2024-01-09 00:25

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0010_toolkit'),
    ]

    operations = [
        migrations.CreateModel(
            name='IEEE_NSU_Student_Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_nsu_student_branch', models.TextField(blank=True, null=True)),
                ('about_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE NSU Student Branch/About Image/')),
                ('chapters_description', models.TextField(blank=True, null=True)),
                ('ras_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE NSU Student Branch/RAS Image/')),
                ('ras_read_more_link', models.CharField(blank=True, max_length=200, null=True)),
                ('pes_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE NSU Student Branch/PES Image/')),
                ('pes_read_more_link', models.CharField(blank=True, max_length=200, null=True)),
                ('ias_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE NSU Student Branch/IAS Image/')),
                ('ias_read_more_link', models.CharField(blank=True, max_length=200, null=True)),
                ('wie_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE NSU Student Branch/WIE Image/')),
                ('wie_read_more_link', models.CharField(blank=True, max_length=200, null=True)),
                ('creative_team_description', models.TextField(blank=True, null=True)),
                ('mission_description', models.TextField(blank=True, null=True)),
                ('mission_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE NSU Student Branch/Mission Image/')),
                ('vision_description', models.TextField(blank=True, null=True)),
                ('vision_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE NSU Student Branch/Vision Image/')),
                ('events_description', models.TextField(blank=True, null=True)),
                ('join_now_link', models.CharField(blank=True, max_length=200, null=True)),
                ('achievements_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'IEEE NSU Student Branch',
            },
        ),
        migrations.CreateModel(
            name='Page_Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=120)),
                ('link', models.URLField(max_length=250)),
            ],
            options={
                'verbose_name': 'Page Link',
            },
        ),
        migrations.AddField(
            model_name='about_ieee',
            name='asia_pacific_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about_ieee',
            name='customer_service_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='about_ieee',
            name='founders_names',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='about_ieee',
            name='ieee_computer_organization_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about_ieee',
            name='join_now_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about_ieee',
            name='learn_more_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about_ieee',
            name='mission_and_vision_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about_ieee',
            name='presidents_names',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ieee_bangladesh_section',
            name='achievements_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ieee_bangladesh_section',
            name='chair_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ieee_bangladesh_section',
            name='chair_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ieee_bangladesh_section',
            name='ieee_bd_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ieee_bangladesh_section',
            name='office_secretary_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ieee_bangladesh_section',
            name='office_secretary_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ieee_bangladesh_section',
            name='secretary_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ieee_bangladesh_section',
            name='secretary_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
