# Generated by Django 4.2.2 on 2024-01-08 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0010_ieee_bangladesh_section_achievements_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ieee_bangladesh_section',
            old_name='office_secretary_email',
            new_name='office_secretary_number',
        ),
    ]
