# Generated by Django 4.2.2 on 2023-12-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0010_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
