# Generated by Django 4.2.2 on 2024-01-06 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0009_galleryimages_galleryvideos'),
        ('main_website', '0011_exemplarymembers_member_picture_and_more'),
    ]

    operations = [
    ]
