# Generated by Django 4.2.2 on 2024-01-08 21:19

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0011_rename_office_secretary_email_ieee_bangladesh_section_office_secretary_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='IEEE_NSU_Student_Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_nsu_student_branch', models.TextField(blank=True, null=True)),
                ('about_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE NSU Student Branch/About Image/')),
                ('chapters_description', models.TextField(blank=True, null=True)),
                ('ras_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE NSU Student Branch/RAS Image/')),
                ('ras_read_more_link', models.CharField(blank=True, max_length=200, null=True)),
                ('pes_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE NSU Student Branch/PES Image/')),
                ('pes_read_more_link', models.CharField(blank=True, max_length=200, null=True)),
                ('ias_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE NSU Student Branch/IAS Image/')),
                ('ias_read_more_link', models.CharField(blank=True, max_length=200, null=True)),
                ('wie_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE NSU Student Branch/WIE Image/')),
                ('wie_read_more_link', models.CharField(blank=True, max_length=200, null=True)),
                ('creative_team_description', models.TextField(blank=True, null=True)),
                ('mission_description', models.TextField(blank=True, null=True)),
                ('mission_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE NSU Student Branch/Mission Image/')),
                ('vision_description', models.TextField(blank=True, null=True)),
                ('vision_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE NSU Student Branch/Vision Image/')),
                ('events_description', models.TextField(blank=True, null=True)),
                ('join_now_link', models.CharField(blank=True, max_length=200, null=True)),
                ('achievements_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Page Link',
            },
        ),
    ]
