# Generated by Django 4.2.2 on 2024-01-09 00:50

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0011_ieee_nsu_student_branch_page_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IEEE_Region_10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ieee_region_10_description', models.TextField(blank=True, null=True)),
                ('ieee_region_10_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE Region 10/Region 10 Image/')),
                ('ieee_region_10_history_link', models.CharField(blank=True, max_length=200, null=True)),
                ('young_professionals_description', models.TextField(blank=True, null=True)),
                ('young_professionals_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE Region 10/Young Professionals Image/')),
                ('women_in_engineering_ddescription', models.TextField(blank=True, null=True)),
                ('student_and_member_activities_description', models.TextField(blank=True, null=True)),
                ('educational_activities_and_involvements_description', models.TextField(blank=True, null=True)),
                ('industry_relations_description', models.TextField(blank=True, null=True)),
                ('membership_development_description', models.TextField(blank=True, null=True)),
                ('membership_development_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE Region 10/Membership Development Image/')),
                ('background_picture_parallax', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE Region 10/Parallax Background Image/')),
                ('events_and_conference_description', models.TextField(blank=True, null=True)),
                ('events_and_conference_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE Region 10/Events and Conference Image/')),
                ('home_page_link', models.CharField(blank=True, max_length=200, null=True)),
                ('website_link', models.CharField(blank=True, max_length=200, null=True)),
                ('membership_inquiry_link', models.CharField(blank=True, max_length=200, null=True)),
                ('for_volunteers_link', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'IEEE Region 10',
            },
        ),
    ]
