# Generated by Django 4.2.2 on 2024-01-09 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0012_ieee_region_10'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ_Question_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'FAQ Category',
            },
        ),
        migrations.CreateModel(
            name='FAQ_Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_website.faq_question_category')),
            ],
            options={
                'verbose_name': 'FAQ Category',
            },
        ),
    ]
