# Generated by Django 4.2.2 on 2024-01-08 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0012_ieee_nsu_student_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ieee_nsu_student_branch',
            options={'verbose_name': 'IEEE NSU Student Branch'},
        ),
    ]
