# Generated by Django 4.2.2 on 2023-08-15 07:36

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0013_alter_homepagebannerpicturewithtext_banner_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagebannerpicturewithtext',
            name='button_text',
            field=models.CharField(default='About INSB', max_length=50),
        ),
        migrations.AddField(
            model_name='homepagebannerpicturewithtext',
            name='button_url',
            field=models.URLField(default='#'),
        ),
        migrations.AlterField(
            model_name='homepagebannerpicturewithtext',
            name='banner_picture',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/homepage/banner_pictures'),
        ),
    ]
