# Generated by Django 4.2.2 on 2024-01-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0013_alter_galleryvideos_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryvideos',
            name='video_title',
            field=models.CharField(default='INSB Videos', max_length=100),
            preserve_default=False,
        ),
    ]
