# Generated by Django 4.2.2 on 2023-08-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0014_homepagebannerpicturewithtext_button_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagebannerpicturewithtext',
            name='button_url',
            field=models.CharField(default='#', max_length=200),
        ),
    ]
