# Generated by Django 4.2.2 on 2024-01-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0014_alter_faq_questions_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq_question_category',
            name='priority',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
