# Generated by Django 4.2.2 on 2023-09-25 10:48

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0015_alter_homepagebannerpicturewithtext_button_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='RibbonPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=('middle', 'center'), force_format='JPEG', keep_meta=True, quality=80, scale=1.0, size=(1600, 450), upload_to='main_website_files/homepage/ribbon_picture')),
            ],
            options={
                'verbose_name': 'Ribbon Picture in Homepage',
            },
        ),
    ]
