# Generated by Django 4.2.2 on 2023-12-20 07:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0015_alter_blog_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('authors', ckeditor.fields.RichTextField(max_length=500)),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': 'Research Papers',
            },
        ),
    ]
