# Generated by Django 4.2.2 on 2024-01-09 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0015_faq_question_category_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq_question_category',
            name='priority',
        ),
    ]
