# Generated by Django 4.2.2 on 2023-09-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0016_ribbonpicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ribbonpicture',
            name='image',
            field=models.ImageField(upload_to='main_website_files/homepage/ribbon_picture'),
        ),
    ]
