# Generated by Django 4.2.2 on 2023-12-20 07:59

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0016_researchpaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Research Category',
            },
        ),
        migrations.DeleteModel(
            name='ResearchPaper',
        ),
        migrations.AddField(
            model_name='research_papers',
            name='publish_date',
            field=models.DateField(default='2030-12-08'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='research_papers',
            name='publish_research',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='research_papers',
            name='short_description',
            field=ckeditor.fields.RichTextField(default='ggez', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='research_papers',
            name='author_names',
            field=ckeditor.fields.RichTextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='research_papers',
            name='research_banner_picture',
            field=models.ImageField(default='main_website_files/Research_pictures/default_research_banner_picture.png', upload_to='main_website_files/Research_pictures/'),
        ),
        migrations.AlterField(
            model_name='research_papers',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='research_papers',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_website.researchcategory'),
        ),
    ]
