# Generated by Django 4.2.2 on 2023-12-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0017_researchcategory_delete_researchpaper_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research_papers',
            name='publish_date',
            field=models.DateField(help_text='<br>Please use the following format: <em>YYYY-MM-DD</em>.'),
        ),
    ]
