# Generated by Django 3.2.16 on 2023-10-03 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0017_alter_ribbonpicture_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RibbonPicture',
            new_name='BannerPictureWithStat',
        ),
        migrations.AlterModelOptions(
            name='bannerpicturewithstat',
            options={'verbose_name': 'Banner Picture with Statistics in Homepage'},
        ),
    ]
