# Generated by Django 4.2.2 on 2023-10-14 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0017_alter_ribbonpicture_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ribbonpicture',
            options={'verbose_name': 'Banner Picture with Statistics in Homepage'},
        ),
    ]
