# Generated by Django 4.2.2 on 2024-01-12 17:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0017_volunteerofthemonth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='Write within 1000 words!', max_length=10000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_description',
            field=ckeditor.fields.RichTextField(help_text='Write within 200 words!', max_length=1000),
        ),
    ]
