# Generated by Django 4.2.2 on 2024-01-13 00:04

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0018_alter_blog_description_alter_blog_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_ieee',
            name='about_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE/About Image/'),
        ),
        migrations.AlterField(
            model_name='about_ieee',
            name='community_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE/Community Image/'),
        ),
        migrations.AlterField(
            model_name='about_ieee',
            name='innovations_and_developments_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE/Innovation Development Image/'),
        ),
        migrations.AlterField(
            model_name='about_ieee',
            name='quality_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE/Quality Image/'),
        ),
        migrations.AlterField(
            model_name='about_ieee',
            name='students_and_member_activities_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE/Student Member Activity Image/'),
        ),
        migrations.AlterField(
            model_name='bannerpicturewithstat',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/homepage/ribbon_picture'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_banner_picture',
            field=django_resized.forms.ResizedImageField(crop=None, default='main_website_files/Blog_banner_pictures/default_blog_banner_picture.png', force_format=None, keep_meta=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/Blog_pictures/'),
        ),
        migrations.AlterField(
            model_name='galleryimages',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/gallery_pictures/'),
        ),
        migrations.AlterField(
            model_name='homepagetopbanner',
            name='banner_picture',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/homepage/banner_pictures'),
        ),
        migrations.AlterField(
            model_name='ieee_bangladesh_section',
            name='ieee_bangladesh_logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE Bangladesh Section/logo/'),
        ),
        migrations.AlterField(
            model_name='ieee_bangladesh_section',
            name='member_and_volunteer_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE Bangladesh Section/member_volunteer_picture/'),
        ),
        migrations.AlterField(
            model_name='ieee_bangladesh_section_gallery',
            name='picture',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE Bangladesh Section/Gallery/'),
        ),
        migrations.AlterField(
            model_name='ieee_nsu_student_branch',
            name='about_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE NSU Student Branch/About Image/'),
        ),
        migrations.AlterField(
            model_name='ieee_nsu_student_branch',
            name='ias_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE NSU Student Branch/IAS Image/'),
        ),
        migrations.AlterField(
            model_name='ieee_nsu_student_branch',
            name='mission_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE NSU Student Branch/Mission Image/'),
        ),
        migrations.AlterField(
            model_name='ieee_nsu_student_branch',
            name='pes_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE NSU Student Branch/PES Image/'),
        ),
        migrations.AlterField(
            model_name='ieee_nsu_student_branch',
            name='ras_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE NSU Student Branch/RAS Image/'),
        ),
        migrations.AlterField(
            model_name='ieee_nsu_student_branch',
            name='vision_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE NSU Student Branch/Vision Image/'),
        ),
        migrations.AlterField(
            model_name='ieee_nsu_student_branch',
            name='wie_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE NSU Student Branch/WIE Image/'),
        ),
        migrations.AlterField(
            model_name='ieee_region_10',
            name='background_picture_parallax',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE Region 10/Parallax Background Image/'),
        ),
        migrations.AlterField(
            model_name='ieee_region_10',
            name='events_and_conference_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE Region 10/Events and Conference Image/'),
        ),
        migrations.AlterField(
            model_name='ieee_region_10',
            name='ieee_region_10_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE Region 10/Region 10 Image/'),
        ),
        migrations.AlterField(
            model_name='ieee_region_10',
            name='membership_development_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE Region 10/Membership Development Image/'),
        ),
        migrations.AlterField(
            model_name='ieee_region_10',
            name='young_professionals_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/About/IEEE Region 10/Young Professionals Image/'),
        ),
        migrations.AlterField(
            model_name='magazines',
            name='magazine_picture',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/magazine_pictures/'),
        ),
        migrations.AlterField(
            model_name='toolkit',
            name='picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/toolkit_pictures/'),
        ),
    ]
