# Generated by Django 4.2.2 on 2023-12-22 05:31

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0029_rename_is_volunteer_roles_and_position_is_core_volunteer'),
        ('main_website', '0018_alter_research_papers_publish_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magazine_title', models.CharField(max_length=100)),
                ('magazine_short_description', ckeditor.fields.RichTextField(max_length=400)),
                ('magazine_picture', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/magazine_pictures/')),
                ('magazine_file', models.FileField(upload_to='main_website_files/Magazine/')),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='port.chapters_society_and_affinity_groups')),
            ],
            options={
                'verbose_name': 'Magazine',
            },
        ),
    ]
