# Generated by Django 3.2.16 on 2023-10-18 14:53

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0018_alter_ribbonpicture_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerPictureWithStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=80, scale=1.0, size=[1920, 1080], upload_to='main_website_files/homepage/ribbon_picture')),
            ],
            options={
                'verbose_name': 'Banner Picture with Statistics in Homepage',
            },
        ),
        migrations.DeleteModel(
            name='RibbonPicture',
        ),
    ]
