# Generated by Django 3.2.16 on 2023-10-18 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0019_auto_20231018_2053'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannerPictureWithStat',
        ),
    ]
