# Generated by Django 4.2.2 on 2023-12-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0019_magazines'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazines',
            name='publish_date',
            field=models.DateField(default='2030-2-18'),
            preserve_default=False,
        ),
    ]
