# Generated by Django 4.2.2 on 2023-10-18 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0018_alter_ribbonpicture_options'),
        ('main_website', '0019_alter_bannerpicturewithstat_image'),
    ]

    operations = [
    ]
