# Generated by Django 4.2.2 on 2023-12-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0020_magazines_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazines',
            name='publish_date',
            field=models.DateField(help_text='<br>Please use the following format: <em>YYYY-MM-DD</em>.'),
        ),
    ]
