# Generated by Django 3.2.16 on 2023-09-06 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('port', '0015_auto_20230906_1813'),
        ('users', '0042_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ieee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.members')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='port.society_chapters_ag_roles_and_positions')),
            ],
        ),
    ]
