# Generated by Django 4.2.2 on 2023-09-07 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0015_auto_20230906_1813'),
        ('ieee_nsu_sb_pes_sbc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pesmembers',
            options={'verbose_name': 'PES Registered Members'},
        ),
        migrations.AddField(
            model_name='pesmembers',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='port.society_chapters_ag_teams'),
        ),
    ]
