# Generated by Django 4.2.2 on 2023-09-07 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ieee_nsu_sb_pes_sbc', '0002_alter_pesmembers_options_pesmembers_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesmembers',
            name='position',
        ),
        migrations.RemoveField(
            model_name='pesmembers',
            name='team',
        ),
    ]
