# Generated by Django 4.2.2 on 2023-09-07 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0017_remove_society_chapters_ag_teams_chapter_id_and_more'),
        ('ieee_nsu_sb_pes_sbc', '0003_remove_pesmembers_position_remove_pesmembers_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesmembers',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='port.roles_and_position'),
        ),
        migrations.AddField(
            model_name='pesmembers',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='port.teams'),
        ),
    ]
