# Generated by Django 4.2.2 on 2023-10-29 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_alter_user_options'),
        ('ieee_nsu_sb_pes_sbc', '0004_pesmembers_position_pesmembers_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesDataAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewal_data_access', models.BooleanField(default=False)),
                ('ieee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.members')),
            ],
            options={
                'verbose_name': 'PES Data Access',
            },
        ),
    ]
