# Generated by Django 4.0.5 on 2023-01-20 18:55

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Proposal_Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('proposal_template', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='Template-Event Proposal'), upload_to='')),
            ],
            options={
                'verbose_name': 'Event Proposal Templates',
            },
        ),
        migrations.CreateModel(
            name='Permission_criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_name', models.CharField(max_length=50)),
                ('template', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='Permission Templates'), upload_to='')),
            ],
            options={
                'verbose_name': 'Permission Categories',
            },
        ),
        migrations.CreateModel(
            name='Venue_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Venue',
            },
        ),
    ]
