# Generated by Django 4.2.2 on 2024-01-18 05:43

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_and_management_team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_proposal_template',
            name='proposal_template',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='Template-Event-Proposal'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='permission_criteria',
            name='template',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='Permission-Templates'), upload_to=''),
        ),
    ]
